import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { orders, payments, products, users } from "./core";

const id = () => uuid("id").defaultRandom().primaryKey();
const createdAt = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const refundStatus = pgEnum("refund_status",["REQUESTED","PROCESSING","SUCCEEDED","FAILED","CANCELLED"]);
export const couponType = pgEnum("coupon_type",["FIXED","PERCENT"]);
export const couponRedemptionStatus = pgEnum("coupon_redemption_status",["RESERVED","CONSUMED","RELEASED"]);
export const reconciliationStatus = pgEnum("reconciliation_status",["MATCHED","MISMATCH","MISSING_INTERNAL","MISSING_PROVIDER"]);

export const paymentAttempts = pgTable("payment_attempts", { id:id(), orderId:uuid("order_id").references(()=>orders.id,{onDelete:"cascade"}).notNull(), provider:varchar("provider",{length:30}).notNull(), providerOrderId:varchar("provider_order_id",{length:150}), checkoutReference:text("checkout_reference"), status:varchar("status",{length:40}).notNull(), idempotencyKey:varchar("idempotency_key",{length:100}).notNull(), amountPaise:integer("amount_paise").notNull(), currency:varchar("currency",{length:3}).default("INR").notNull(), expiresAt:timestamp("expires_at",{withTimezone:true}), failureCode:varchar("failure_code",{length:100}), rawMetadata:jsonb("raw_metadata").$type<Record<string,unknown>>(), createdAt:createdAt(), updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull() },t=>[uniqueIndex("payment_attempts_idempotency_uq").on(t.idempotencyKey),uniqueIndex("payment_attempts_provider_order_uq").on(t.provider,t.providerOrderId),index("payment_attempts_order_idx").on(t.orderId,t.createdAt),check("payment_attempts_amount_check",sql`${t.amountPaise} > 0`)]);
export const refunds = pgTable("refunds", { id:id(), paymentId:uuid("payment_id").references(()=>payments.id).notNull(), provider:varchar("provider",{length:30}).notNull(), providerRefundId:varchar("provider_refund_id",{length:150}), idempotencyKey:varchar("idempotency_key",{length:100}).notNull(), status:refundStatus("status").default("REQUESTED").notNull(), amountPaise:integer("amount_paise").notNull(), reason:text("reason").notNull(), revokeAccess:boolean("revoke_access").default(false).notNull(), requestedBy:uuid("requested_by").references(()=>users.id).notNull(), processedAt:timestamp("processed_at",{withTimezone:true}), failureCode:varchar("failure_code",{length:100}), createdAt:createdAt(), updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull() },t=>[uniqueIndex("refunds_provider_id_uq").on(t.provider,t.providerRefundId),uniqueIndex("refunds_idempotency_uq").on(t.idempotencyKey),index("refunds_payment_idx").on(t.paymentId),check("refunds_amount_check",sql`${t.amountPaise} > 0`)]);
export const coupons = pgTable("coupons", { id:id(), code:varchar("code",{length:60}).notNull(), type:couponType("type").notNull(), value:integer("value").notNull(), currency:varchar("currency",{length:3}), maxDiscountPaise:integer("max_discount_paise"), minOrderPaise:integer("min_order_paise").default(0).notNull(), totalLimit:integer("total_limit"), perUserLimit:integer("per_user_limit").default(1).notNull(), startsAt:timestamp("starts_at",{withTimezone:true}), endsAt:timestamp("ends_at",{withTimezone:true}), active:boolean("active").default(true).notNull(), createdBy:uuid("created_by").references(()=>users.id).notNull(), createdAt:createdAt(), updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull() },t=>[uniqueIndex("coupons_code_uq").on(t.code),index("coupons_active_window_idx").on(t.active,t.startsAt,t.endsAt),check("coupons_value_check",sql`${t.value} > 0 and (${t.type} <> 'PERCENT' or ${t.value} <= 10000) and ${t.minOrderPaise} >= 0 and (${t.maxDiscountPaise} is null or ${t.maxDiscountPaise} > 0) and (${t.totalLimit} is null or ${t.totalLimit} > 0) and ${t.perUserLimit} > 0 and (${t.endsAt} is null or ${t.startsAt} is null or ${t.endsAt} > ${t.startsAt})`)]);
export const couponProducts = pgTable("coupon_products", { couponId:uuid("coupon_id").references(()=>coupons.id,{onDelete:"cascade"}).notNull(), productId:uuid("product_id").references(()=>products.id,{onDelete:"cascade"}).notNull() },t=>[primaryKey({columns:[t.couponId,t.productId]})]);
export const couponRedemptions = pgTable("coupon_redemptions", { id:id(), couponId:uuid("coupon_id").references(()=>coupons.id).notNull(), userId:uuid("user_id").references(()=>users.id).notNull(), orderId:uuid("order_id").references(()=>orders.id).notNull(), status:couponRedemptionStatus("status").default("RESERVED").notNull(), discountPaise:integer("discount_paise").notNull(), expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(), consumedAt:timestamp("consumed_at",{withTimezone:true}), releasedAt:timestamp("released_at",{withTimezone:true}), createdAt:createdAt() },t=>[uniqueIndex("coupon_redemptions_order_uq").on(t.orderId),index("coupon_redemptions_user_idx").on(t.couponId,t.userId,t.status),index("coupon_redemptions_expiry_idx").on(t.status,t.expiresAt),check("coupon_redemptions_discount_check",sql`${t.discountPaise} > 0`)]);
export const invoices = pgTable("invoices", { id:id(), orderId:uuid("order_id").references(()=>orders.id).notNull(), number:varchar("number",{length:80}).notNull(), objectKey:text("object_key"), issuedAt:timestamp("issued_at",{withTimezone:true}).defaultNow().notNull(), billingSnapshot:jsonb("billing_snapshot").$type<Record<string,unknown>>().notNull() },t=>[uniqueIndex("invoices_number_uq").on(t.number),uniqueIndex("invoices_order_uq").on(t.orderId)]);
export const reconciliationRuns = pgTable("reconciliation_runs", { id:id(), provider:varchar("provider",{length:30}).notNull(), startedAt:timestamp("started_at",{withTimezone:true}).defaultNow().notNull(), completedAt:timestamp("completed_at",{withTimezone:true}), cursor:text("cursor"), error:text("error") });
export const reconciliationItems = pgTable("reconciliation_items", { id:id(), runId:uuid("run_id").references(()=>reconciliationRuns.id,{onDelete:"cascade"}).notNull(), paymentId:uuid("payment_id").references(()=>payments.id), providerPaymentId:varchar("provider_payment_id",{length:150}), status:reconciliationStatus("status").notNull(), expectedAmountPaise:integer("expected_amount_paise"), providerAmountPaise:integer("provider_amount_paise"), details:jsonb("details").$type<Record<string,unknown>>() },t=>[index("reconciliation_items_run_idx").on(t.runId,t.status)]);
