import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { materials, questions, users } from "./core";

const id = () => uuid("id").defaultRandom().primaryKey();
const createdAt = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const importStatus = pgEnum("import_status",["UPLOADED","VALIDATING","INVALID","READY","IMPORTED","FAILED"]);

export const questionRevisions = pgTable("question_revisions", { id:id(), questionId:uuid("question_id").references(()=>questions.id,{onDelete:"cascade"}).notNull(), version:integer("version").notNull(), stem:text("stem").notNull(), explanation:text("explanation"), marks:numeric("marks",{precision:8,scale:2}).notNull(), negativeMarks:numeric("negative_marks",{precision:8,scale:2}).default("0").notNull(), answerConfig:jsonb("answer_config").$type<Record<string,unknown>>().notNull(), createdBy:uuid("created_by").references(()=>users.id).notNull(), reviewedBy:uuid("reviewed_by").references(()=>users.id), publishedAt:timestamp("published_at",{withTimezone:true}), createdAt:createdAt() },t=>[uniqueIndex("question_revisions_version_uq").on(t.questionId,t.version)]);
export const questionRevisionOptions = pgTable("question_revision_options", { id:id(), revisionId:uuid("revision_id").references(()=>questionRevisions.id,{onDelete:"cascade"}).notNull(), stableKey:varchar("stable_key",{length:50}).notNull(), body:text("body").notNull(), isCorrect:boolean("is_correct").default(false).notNull(), sortOrder:integer("sort_order").notNull() },t=>[uniqueIndex("question_revision_options_key_uq").on(t.revisionId,t.stableKey),uniqueIndex("question_revision_options_order_uq").on(t.revisionId,t.sortOrder)]);
export const materialVersions = pgTable("material_versions", { id:id(), materialId:uuid("material_id").references(()=>materials.id,{onDelete:"cascade"}).notNull(), version:integer("version").notNull(), title:varchar("title",{length:200}).notNull(), body:text("body"), privateObjectKey:text("private_object_key"), checksum:varchar("checksum",{length:128}), sizeBytes:integer("size_bytes"), createdBy:uuid("created_by").references(()=>users.id).notNull(), publishedAt:timestamp("published_at",{withTimezone:true}), createdAt:createdAt() },t=>[uniqueIndex("material_versions_version_uq").on(t.materialId,t.version)]);
export const contentImportJobs = pgTable("content_import_jobs", { id:id(), type:varchar("type",{length:40}).notNull(), status:importStatus("status").default("UPLOADED").notNull(), objectKey:text("object_key").notNull(), totalRows:integer("total_rows").default(0).notNull(), validRows:integer("valid_rows").default(0).notNull(), invalidRows:integer("invalid_rows").default(0).notNull(), requestedBy:uuid("requested_by").references(()=>users.id).notNull(), error:text("error"), createdAt:createdAt(), completedAt:timestamp("completed_at",{withTimezone:true}) },t=>[index("content_import_jobs_status_idx").on(t.status,t.createdAt)]);
export const contentImportErrors = pgTable("content_import_errors", { id:id(), jobId:uuid("job_id").references(()=>contentImportJobs.id,{onDelete:"cascade"}).notNull(), rowNumber:integer("row_number").notNull(), field:varchar("field",{length:100}), code:varchar("code",{length:100}).notNull(), message:text("message").notNull(), rawValue:text("raw_value") },t=>[index("content_import_errors_job_idx").on(t.jobId,t.rowNumber)]);
