import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { entitlements, materials, notifications, orders, users } from "./core";
import { materialVersions } from "./content";

const id = () => uuid("id").defaultRandom().primaryKey();
const createdAt = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const ticketStatus = pgEnum("ticket_status",["OPEN","IN_PROGRESS","WAITING_FOR_STUDENT","RESOLVED","CLOSED"]);
export const jobStatus = pgEnum("job_status",["PENDING","RUNNING","SUCCEEDED","FAILED","DEAD"]);

export const materialAccessLogs = pgTable("material_access_logs", { id:id(), userId:uuid("user_id").references(()=>users.id).notNull(), materialId:uuid("material_id").references(()=>materials.id).notNull(), versionId:uuid("version_id").references(()=>materialVersions.id).notNull(), entitlementId:uuid("entitlement_id").references(()=>entitlements.id), accessSource:varchar("access_source",{length:20}).notNull(), action:varchar("action",{length:30}).notNull(), requestId:varchar("request_id",{length:100}), ipHash:text("ip_hash"), createdAt:createdAt() },t=>[index("material_access_user_idx").on(t.userId,t.createdAt),index("material_access_material_idx").on(t.materialId,t.createdAt),check("material_access_source_check",sql`${t.accessSource} in ('FREE','ENTITLEMENT')`),check("material_access_entitlement_check",sql`(${t.accessSource} = 'FREE' and ${t.entitlementId} is null) or (${t.accessSource} = 'ENTITLEMENT' and ${t.entitlementId} is not null)`),check("material_access_action_check",sql`${t.action} in ('VIEW','DOWNLOAD')`)]);
export const securityEvents = pgTable("security_events", { id:id(), userId:uuid("user_id").references(()=>users.id,{onDelete:"set null"}), type:varchar("type",{length:80}).notNull(), severity:varchar("severity",{length:20}).notNull(), requestId:varchar("request_id",{length:100}), ipHash:text("ip_hash"), userAgent:text("user_agent"), metadata:jsonb("metadata").$type<Record<string,unknown>>(), createdAt:createdAt() },t=>[index("security_events_user_idx").on(t.userId,t.createdAt),index("security_events_type_idx").on(t.type,t.createdAt)]);
export const supportTickets = pgTable("support_tickets", { id:id(), userId:uuid("user_id").references(()=>users.id).notNull(), orderId:uuid("order_id").references(()=>orders.id), subject:varchar("subject",{length:200}).notNull(), category:varchar("category",{length:60}).notNull(), priority:varchar("priority",{length:20}).default("NORMAL").notNull(), status:ticketStatus("status").default("OPEN").notNull(), assignedTo:uuid("assigned_to").references(()=>users.id), createdAt:createdAt(), updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull(), resolvedAt:timestamp("resolved_at",{withTimezone:true}) },t=>[index("support_tickets_user_idx").on(t.userId,t.createdAt),index("support_tickets_queue_idx").on(t.status,t.priority,t.createdAt)]);
export const supportMessages = pgTable("support_messages", { id:id(), ticketId:uuid("ticket_id").references(()=>supportTickets.id,{onDelete:"cascade"}).notNull(), authorId:uuid("author_id").references(()=>users.id).notNull(), body:text("body").notNull(), attachmentObjectKey:text("attachment_object_key"), internal:boolean("internal").default(false).notNull(), createdAt:createdAt() },t=>[index("support_messages_ticket_idx").on(t.ticketId,t.createdAt)]);
export const backgroundJobs = pgTable("background_jobs", { id:id(), type:varchar("type",{length:80}).notNull(), deduplicationKey:varchar("deduplication_key",{length:150}), status:jobStatus("status").default("PENDING").notNull(), payload:jsonb("payload").$type<Record<string,unknown>>().notNull(), attempts:integer("attempts").default(0).notNull(), maxAttempts:integer("max_attempts").default(5).notNull(), runAt:timestamp("run_at",{withTimezone:true}).defaultNow().notNull(), lockedAt:timestamp("locked_at",{withTimezone:true}), lockedBy:varchar("locked_by",{length:100}), lastError:text("last_error"), createdAt:createdAt(), completedAt:timestamp("completed_at",{withTimezone:true}) },t=>[uniqueIndex("background_jobs_dedupe_uq").on(t.deduplicationKey),index("background_jobs_queue_idx").on(t.status,t.runAt)]);
export const notificationDeliveries = pgTable("notification_deliveries", { id:id(), notificationId:uuid("notification_id").references(()=>notifications.id,{onDelete:"cascade"}).notNull(), channel:varchar("channel",{length:30}).notNull(), provider:varchar("provider",{length:30}), providerMessageId:varchar("provider_message_id",{length:150}), status:varchar("status",{length:30}).notNull(), attempts:integer("attempts").default(0).notNull(), lastError:text("last_error"), sentAt:timestamp("sent_at",{withTimezone:true}), createdAt:createdAt() },t=>[uniqueIndex("notification_delivery_channel_uq").on(t.notificationId,t.channel),uniqueIndex("notification_delivery_provider_uq").on(t.provider,t.providerMessageId),index("notification_delivery_status_idx").on(t.status,t.createdAt)]);
