import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { attempts, questionType, questions, testSections, tests, topics, users } from "./core";
import { questionRevisions } from "./content";

const id = () => uuid("id").defaultRandom().primaryKey();
const createdAt = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const resultStatus = pgEnum("result_status",["PENDING","CALCULATED","PUBLISHED","WITHHELD","REVISED"]);

export const testSchedules = pgTable("test_schedules", { id:id(), testId:uuid("test_id").references(()=>tests.id,{onDelete:"cascade"}).notNull(), startsAt:timestamp("starts_at",{withTimezone:true}).notNull(), endsAt:timestamp("ends_at",{withTimezone:true}).notNull(), lateJoinMinutes:integer("late_join_minutes").default(15).notNull(), resultReleaseAt:timestamp("result_release_at",{withTimezone:true}), rankingEnabled:boolean("ranking_enabled").default(false).notNull(), cohortKey:varchar("cohort_key",{length:100}), createdAt:createdAt() },t=>[index("test_schedules_window_idx").on(t.startsAt,t.endsAt),index("test_schedules_test_idx").on(t.testId)]);
export const attemptSchedules = pgTable("attempt_schedules", { attemptId:uuid("attempt_id").references(()=>attempts.id,{onDelete:"cascade"}).notNull(), scheduleId:uuid("schedule_id").references(()=>testSchedules.id,{onDelete:"restrict"}).notNull() },t=>[primaryKey({columns:[t.attemptId]}),index("attempt_schedules_schedule_idx").on(t.scheduleId)]);
export const attemptQuestionSnapshots = pgTable("attempt_question_snapshots", { id:id(), attemptId:uuid("attempt_id").references(()=>attempts.id,{onDelete:"cascade"}).notNull(), questionId:uuid("question_id").references(()=>questions.id).notNull(), revisionId:uuid("revision_id").references(()=>questionRevisions.id).notNull(), sectionId:uuid("section_id").references(()=>testSections.id).notNull(), topicId:uuid("topic_id").references(()=>topics.id).notNull(), type:questionType("type").notNull(), position:integer("position").notNull(), stem:text("stem").notNull(), explanation:text("explanation"), marks:numeric("marks",{precision:8,scale:2}).notNull(), negativeMarks:numeric("negative_marks",{precision:8,scale:2}).notNull(), answerConfig:jsonb("answer_config").$type<Record<string,unknown>>().notNull() },t=>[uniqueIndex("attempt_snapshot_position_uq").on(t.attemptId,t.position),uniqueIndex("attempt_snapshot_question_uq").on(t.attemptId,t.questionId)]);
export const attemptOptionSnapshots = pgTable("attempt_option_snapshots", { id:id(), questionSnapshotId:uuid("question_snapshot_id").references(()=>attemptQuestionSnapshots.id,{onDelete:"cascade"}).notNull(), stableKey:varchar("stable_key",{length:50}).notNull(), body:text("body").notNull(), isCorrect:boolean("is_correct").notNull(), position:integer("position").notNull() },t=>[uniqueIndex("attempt_option_position_uq").on(t.questionSnapshotId,t.position)]);
export const attemptSectionStates = pgTable("attempt_section_states", { attemptId:uuid("attempt_id").references(()=>attempts.id,{onDelete:"cascade"}).notNull(), sectionId:uuid("section_id").references(()=>testSections.id).notNull(), startedAt:timestamp("started_at",{withTimezone:true}), deadlineAt:timestamp("deadline_at",{withTimezone:true}), submittedAt:timestamp("submitted_at",{withTimezone:true}) },t=>[primaryKey({columns:[t.attemptId,t.sectionId]})]);
export const results = pgTable("results", { id:id(), attemptId:uuid("attempt_id").references(()=>attempts.id,{onDelete:"cascade"}).notNull(), version:integer("version").default(1).notNull(), status:resultStatus("status").default("PENDING").notNull(), score:numeric("score",{precision:10,scale:2}).notNull(), maxScore:numeric("max_score",{precision:10,scale:2}).notNull(), correctCount:integer("correct_count").notNull(), incorrectCount:integer("incorrect_count").notNull(), unansweredCount:integer("unanswered_count").notNull(), timeSpentSeconds:integer("time_spent_seconds").notNull(), calculatedAt:timestamp("calculated_at",{withTimezone:true}).defaultNow().notNull(), publishedAt:timestamp("published_at",{withTimezone:true}), revisedBy:uuid("revised_by").references(()=>users.id), revisionReason:text("revision_reason"), createdAt:createdAt() },t=>[uniqueIndex("results_attempt_version_uq").on(t.attemptId,t.version),index("results_status_idx").on(t.status,t.publishedAt)]);
export const sectionResults = pgTable("section_results", { resultId:uuid("result_id").references(()=>results.id,{onDelete:"cascade"}).notNull(), sectionId:uuid("section_id").references(()=>testSections.id).notNull(), score:numeric("score",{precision:10,scale:2}).notNull(), maxScore:numeric("max_score",{precision:10,scale:2}).notNull(), correctCount:integer("correct_count").notNull(), incorrectCount:integer("incorrect_count").notNull(), unansweredCount:integer("unanswered_count").notNull(), timeSpentSeconds:integer("time_spent_seconds").notNull() },t=>[primaryKey({columns:[t.resultId,t.sectionId]})]);
export const topicResults = pgTable("topic_results", { resultId:uuid("result_id").references(()=>results.id,{onDelete:"cascade"}).notNull(), topicId:uuid("topic_id").references(()=>topics.id).notNull(), score:numeric("score",{precision:10,scale:2}).notNull(), maxScore:numeric("max_score",{precision:10,scale:2}).notNull(), correctCount:integer("correct_count").notNull(), attemptedCount:integer("attempted_count").notNull() },t=>[primaryKey({columns:[t.resultId,t.topicId]})]);
export const rankSnapshots = pgTable("rank_snapshots", { id:id(), scheduleId:uuid("schedule_id").references(()=>testSchedules.id,{onDelete:"cascade"}).notNull(), version:integer("version").notNull(), eligibleCount:integer("eligible_count").notNull(), generatedAt:timestamp("generated_at",{withTimezone:true}).defaultNow().notNull(), publishedAt:timestamp("published_at",{withTimezone:true}) },t=>[uniqueIndex("rank_snapshots_version_uq").on(t.scheduleId,t.version)]);
export const rankEntries = pgTable("rank_entries", { snapshotId:uuid("snapshot_id").references(()=>rankSnapshots.id,{onDelete:"cascade"}).notNull(), resultId:uuid("result_id").references(()=>results.id,{onDelete:"cascade"}).notNull(), rank:integer("rank").notNull(), percentile:numeric("percentile",{precision:5,scale:2}).notNull() },t=>[primaryKey({columns:[t.snapshotId,t.resultId]}),index("rank_entries_rank_idx").on(t.snapshotId,t.rank)]);
