import Link from "next/link";
import { WorkspaceShell } from "@/components/workspace-shell";
import { AdminModal } from "@/components/admin-modal";
import { CONTENT_PERMISSIONS } from "@/features/admin-content/permissions";
import { getCatalogExams,getMaterials } from "@/features/admin-catalog/service";
import { MaterialCreateForm,MaterialUploadForm } from "@/features/admin-catalog/ui/forms";
import { requireWorkspacePermission } from "@/features/auth/page-access";
export const metadata={title:"Store & materials"};
export default async function Page(){const auth=await requireWorkspacePermission(CONTENT_PERMISSIONS.manageMaterials);const[materials,exams]=await Promise.all([getMaterials(),getCatalogExams()]);return <WorkspaceShell admin name={auth.user.name} permissions={auth.permissions} section="materials"><header className="admin-page-header"><div><p className="admin-kicker">CONTENT INVENTORY</p><h1>Store & materials</h1><p>Keep PDFs, files and videos organised here. Materials only become available to students after you add them to a live product package.</p></div>{exams.length?<AdminModal label="+ Add material" title="Add study material" description="Upload a file or save a video resource." large><div className="material-create-grid"><section><h3>PDF or file</h3><MaterialUploadForm exams={exams}/></section><section><h3>Video resource</h3><MaterialCreateForm exams={exams}/></section></div></AdminModal>:null}</header><div className="admin-toolbar"><span>{materials.length} saved material{materials.length===1?"":"s"}</span></div>{materials.length?<div className="file-grid">{materials.map(m=><Link className="file-card" href={`/admin/materials/${m.id}`} key={m.id}><span className={m.type==="VIDEO"?"file-type file-video":"file-type"}>{m.type==="VIDEO"?"▶":"PDF"}</span><div><h2>{m.title}</h2><p>{m.examName}</p></div><span className="file-meta">{m.type}</span></Link>)}</div>:<div className="admin-card clean-empty tall"><span className="empty-icon">▤</span><strong>No study material saved</strong><span>Add PDFs, files or video links to start your reusable library.</span></div>}</WorkspaceShell>}
