import Link from "next/link";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { formatMoney } from "@/features/commerce/pricing";
import { getAdminDashboard } from "@/features/operations/admin-dashboard";

export const metadata = { title: "Admin dashboard" };
function MetricIcon({name}:{name:"revenue"|"orders"|"students"|"packages"}){const paths={revenue:<><path d="M4 19V9M10 19V5M16 19v-8M22 19H2"/><path d="m4 7 5-3 5 3 6-5"/></>,orders:<><path d="M5 4h14l-1 16H6zM9 8a3 3 0 0 0 6 0"/></>,students:<><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 5a3 3 0 0 1 0 6M17 14a5 5 0 0 1 4 5"/></>,packages:<><path d="m12 2 9 5-9 5-9-5zM3 12l9 5 9-5M3 17l9 5 9-5"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function change(current:number,previous:number){if(!previous)return current?100:0;return Math.round((current-previous)/previous*100)}
function Trend({value}:{value:number}){return <small className={value<0?"metric-down":"metric-up"}>{value<0?"↓":"↑"} {Math.abs(value)}% <span>vs. previous period</span></small>}
function RevenueChart({items}:{items:{day:Date;revenuePaise:number}[]}){const width=760,height=220,pad=18,max=Math.max(1,...items.map(i=>i.revenuePaise));const points=items.map((item,index)=>`${pad+(index/Math.max(1,items.length-1))*(width-pad*2)},${height-pad-(item.revenuePaise/max)*(height-pad*2)}`).join(" ");const area=`${pad},${height-pad} ${points} ${width-pad},${height-pad}`;return <div className="admin-revenue-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Revenue over selected period"><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ef4b17" stopOpacity=".28"/><stop offset="1" stopColor="#ef4b17" stopOpacity=".02"/></linearGradient></defs>{[.25,.5,.75,1].map(value=><line key={value} x1={pad} x2={width-pad} y1={height-pad-value*(height-pad*2)} y2={height-pad-value*(height-pad*2)} stroke="#ebe8e4" strokeWidth="1"/>)}<polygon points={area} fill="url(#revenueFill)"/><polyline points={points} fill="none" stroke="#ef4b17" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{items.map((item,index)=>{const[x,y]=points.split(" ")[index].split(",");return <circle key={String(item.day)} cx={x} cy={y} r="3.5" fill="#ef4b17"><title>{formatMoney(item.revenuePaise,"INR")}</title></circle>})}</svg><div>{items.filter((_,index)=>index===0||index===items.length-1||index%Math.max(1,Math.floor(items.length/5))===0).map(item=><span key={String(item.day)}>{new Date(item.day).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span>)}</div></div>}
export default async function Page({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const requested = Number((await searchParams).days ?? 30);
  const auth = await requireWorkspace(true);
  const data = await getAdminDashboard(requested);
  const revenueChange=change(data.summary.revenuePaise,data.summary.previousRevenuePaise),orderChange=change(data.summary.orders,data.summary.previousOrders),studentChange=change(data.summary.newUsers,data.summary.previousNewUsers),packageChange=change(data.summary.newLiveProducts,data.summary.previousNewLiveProducts);
  return (
    <WorkspaceShell admin name={auth.user.name} permissions={auth.permissions} section="overview">
      <header className="admin-page-header reference-admin-heading"><div><h1>Dashboard</h1><p>Welcome back! Here&apos;s what&apos;s happening with your store.</p></div><form className="period-selector"><label><span className="sr-only">Reporting period</span><select name="days" defaultValue={data.days}>{[7,14,30,90].map(days=><option key={days} value={days}>Last {days} days</option>)}</select></label><button className="button secondary small" type="submit">Update</button></form></header>
      <section className="dashboard-metrics reference-admin-metrics"><article><i><MetricIcon name="revenue"/></i><span>Revenue</span><strong>{formatMoney(data.summary.revenuePaise,"INR")}</strong><Trend value={revenueChange}/></article><article><i><MetricIcon name="orders"/></i><span>Paid Orders</span><strong>{data.summary.orders}</strong><Trend value={orderChange}/></article><article><i><MetricIcon name="students"/></i><span>Students</span><strong>{data.summary.users}</strong><Trend value={studentChange}/></article><article><i><MetricIcon name="packages"/></i><span>Live Packages</span><strong>{data.summary.liveProducts}</strong><Trend value={packageChange}/></article></section>
      <section className="admin-card reference-revenue-card"><div className="card-heading"><h2>Revenue</h2><form className="period-selector"><select name="days" defaultValue={data.days}>{[7,14,30,90].map(days=><option key={days} value={days}>{days===7?"Daily":`Last ${days} days`}</option>)}</select><button className="sr-only">Update chart</button></form></div><RevenueChart items={data.revenue}/></section>
      <div className="reference-admin-bottom"><section className="admin-card"><div className="card-heading"><h2>Best-selling packages</h2><Link href="/admin/packages">View all</Link></div>{data.topProducts.length?<ol className="top-products">{data.topProducts.map(product=><li key={product.id}><span>{product.name}<small>{product.sold} orders</small></span><strong>{formatMoney(product.revenuePaise,"INR")}</strong></li>)}</ol>:<p className="muted">Sales will appear here.</p>}</section><section className="admin-card flush-card"><div className="card-heading"><h2>Recent orders</h2><Link href="/admin/orders">View all</Link></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order ID</th><th>Student</th><th>Amount</th><th>Date</th></tr></thead><tbody>{data.recentOrders.map(order=><tr key={order.id}><td>#{order.id.slice(0,7).toUpperCase()}</td><td><strong>{order.name}</strong><small>{order.email}</small></td><td>{formatMoney(order.totalPaise,"INR")}</td><td>{new Date(order.createdAt).toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>{!data.recentOrders.length?<div className="clean-empty"><strong>No orders yet</strong></div>:null}</section></div>
    </WorkspaceShell>
  );
}
