"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { operationsRequest, OperationsApiError } from "./api";

function message(error:unknown){return error instanceof OperationsApiError?error.message:"Couldn't complete this request.";}

export function StudentStatusAction({id,status}:{id:string;status:string}) { const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const next=status==="SUSPENDED"?"ACTIVE":"SUSPENDED";return <div className="inline-action"><button className={next==="SUSPENDED"?"button secondary":"button"} disabled={busy} onClick={async()=>{setBusy(true);setError("");try{await operationsRequest(`admin/students/${id}/status`,{status:next},"PATCH");router.refresh();}catch(value){setError(message(value));}finally{setBusy(false);}}}>{busy?"Updating…":next==="SUSPENDED"?"Suspend":"Reactivate"}</button>{error&&<small role="alert">{error}</small>}</div>;}

export function ManagedTicketActions({ticketId,status,priority}:{ticketId:string;status:string;priority:string}) { const router=useRouter();const[busy,setBusy]=useState("");const[error,setError]=useState("");async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("reply");setError("");const form=event.currentTarget;try{await operationsRequest(`admin/support/${ticketId}/messages`,{body:new FormData(form).get("body")});form.reset();router.refresh();}catch(value){setError(message(value));}finally{setBusy("");}}async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("status");setError("");const data=new FormData(event.currentTarget);try{await operationsRequest(`admin/support/${ticketId}`,{status:data.get("status"),priority:data.get("priority")},"PATCH");router.refresh();}catch(value){setError(message(value));}finally{setBusy("");}}return <div className="aside-stack"><form className="admin-form" onSubmit={update}><fieldset disabled={Boolean(busy)}><label className="field"><span>Status</span><select name="status" defaultValue={status}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="WAITING_FOR_STUDENT">Waiting for student</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></label><label className="field"><span>Priority</span><select name="priority" defaultValue={priority}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><button className="button secondary" type="submit">{busy==="status"?"Saving…":"Save ticket state"}</button></fieldset></form>{status!=="CLOSED"&&<form className="admin-form" onSubmit={reply}><fieldset disabled={Boolean(busy)}><label className="field"><span>Reply to student</span><textarea name="body" minLength={2} maxLength={4000} rows={5} required /></label><button className="button" type="submit">{busy==="reply"?"Sending…":"Send reply"}</button></fieldset></form>}{error&&<p className="notice danger" role="alert">{error}</p>}</div>;}

export function RetryDeliveryButton({id}:{id:string}) {const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");return <div className="inline-action"><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setError("");try{await operationsRequest(`admin/notifications/${id}/retry`);router.refresh();}catch(value){setError(message(value));}finally{setBusy(false);}}}>{busy?"Sending…":"Retry email"}</button>{error&&<small role="alert">{error}</small>}</div>;}
