import Link from "next/link";
import { WorkspaceShell } from "@/components/workspace-shell";
import { CONTENT_PERMISSIONS } from "@/features/admin-content/permissions";
import { requireWorkspace } from "@/features/auth/page-access";
import { hasAnyOperationsPermission } from "@/features/operations/permissions";
import { getAdminOperationsSummary, getStudentDashboardSummary } from "@/features/operations/service";

export async function Overview({ adminOnly = false }: { adminOnly?: boolean }) {
  const auth = await requireWorkspace(adminOnly);
  const canManageExams = auth.permissions.includes(CONTENT_PERMISSIONS.manageExams);
  const operations = auth.admin && hasAnyOperationsPermission(auth.permissions) ? await getAdminOperationsSummary() : null;
  const studentSummary = !auth.admin ? await getStudentDashboardSummary(auth.user.id) : null;
  return <WorkspaceShell admin={auth.admin} name={auth.user.name} permissions={auth.permissions} section="overview">
    <div className="page-heading"><span className="eyebrow">{auth.admin ? "YOUR CONTROL CENTRE" : "MAKE ROOM FOR PROGRESS"}</span><h1>{auth.admin ? "Your admin workspace" : "Your preparation starts here"}</h1><p>Welcome, {auth.user.name}. {auth.admin ? "Manage your exams, tests and learning materials." : "Your account is ready. Take a moment to make it yours."}</p></div>
    {operations && <div className="metric-grid"><article className="metric-card"><span>Students</span><strong>{operations.students}</strong><small>registered learners</small></article><article className="metric-card"><span>Open support</span><strong>{operations.openTickets}</strong><small>tickets needing attention</small></article><article className="metric-card"><span>Email queue</span><strong>{operations.pendingDeliveries}</strong><small>pending or failed</small></article><article className="metric-card"><span>Paid orders</span><strong>{operations.paidOrders}</strong><small>completed purchases</small></article></div>}
    {studentSummary && <div className="metric-grid student-summary"><Link className="metric-card" href="/dashboard/tests"><span>My tests</span><strong>{studentSummary.tests}</strong><small>available papers</small></Link><Link className="metric-card" href="/dashboard/library"><span>My library</span><strong>{studentSummary.materials}</strong><small>available resources</small></Link><Link className="metric-card" href="/dashboard/results"><span>Results</span><strong>{studentSummary.results}</strong><small>published reviews</small></Link><Link className="metric-card" href="/dashboard/orders"><span>Orders</span><strong>{studentSummary.orders}</strong><small>purchase records</small></Link><Link className="metric-card" href="/dashboard/notifications"><span>Notifications</span><strong>{studentSummary.unreadNotifications}</strong><small>unread updates</small></Link><Link className="metric-card" href="/dashboard/support"><span>Support</span><strong>{studentSummary.openTickets}</strong><small>open tickets</small></Link></div>}
    <div className="overview-grid">
      <section className="panel welcome-panel"><div className="large-icon" aria-hidden="true">{auth.admin ? "◇" : "○"}</div><h2>{auth.admin ? "Secure by design" : "A space that's yours"}</h2><p>{auth.admin ? "Two-factor authentication is enabled for your administrator account." : "Review your profile and keep your account details up to date."}</p><Link className="button" href={canManageExams ? "/admin/content" : auth.admin ? "/account/security" : "/account/profile"}>{canManageExams ? "Open content workspace" : auth.admin ? "View account security" : "View my profile"}</Link></section>
      <section className="panel"><span className="eyebrow">ACCOUNT AT A GLANCE</span><dl className="account-facts"><div><dt>Email address</dt><dd>{auth.user.email}</dd></div><div><dt>Verification</dt><dd><span className={auth.user.emailVerified ? "status-pill" : "status-pill pending"}>{auth.user.emailVerified ? "Email verified" : "Verification pending"}</span></dd></div><div><dt>Workspace</dt><dd>{auth.admin ? "Administrator" : "Student"}</dd></div></dl></section>
    </div>
    <section className="panel empty-state"><div className="empty-symbol" aria-hidden="true">▤</div><span className="eyebrow">{canManageExams ? "CONTENT" : auth.admin ? "COMING NEXT" : "PRACTICE"}</span><h2>{canManageExams ? "Content management is ready" : auth.admin ? "Your assigned tools will appear here" : "Your mock tests are ready"}</h2><p>{canManageExams ? "Manage exams, questions, tests, packages and imports from this workspace." : auth.admin ? "Navigation is generated from your server-side permissions." : "Open an available test, read its instructions and start or resume your attempt."}</p>{canManageExams ? <Link className="button secondary" href="/admin/exams">Manage exams</Link> : auth.admin ? <span className="quiet-tag">No action needed right now</span> : <Link className="button secondary" href="/dashboard/tests">Open my tests</Link>}</section>
  </WorkspaceShell>;
}
