import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentOrder } from "@/features/commerce/service";
import { commerceIdSchema } from "@/features/commerce/validation";
import { formatMoney } from "@/features/commerce/pricing";

type Order = {id:string;status:string;subtotalPaise:number;discountPaise:number;totalPaise:number;currency:string;couponCode:string|null;createdAt:Date;paidAt:Date|null;provider:string|null;providerPaymentId:string|null;paymentStatus:string|null;items:{productId:string;name:string;pricePaise:number;accessDays:number}[]};
export const metadata={title:"Order details"};
export default async function Page({params}:{params:Promise<{id:string}>}){const auth=await requireWorkspace();if(auth.admin)redirect("/admin");const parsed=commerceIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const raw=await getStudentOrder(parsed.data,auth.user.id);if(!raw)notFound();const order=raw as unknown as Order;return <WorkspaceShell admin={false} name={auth.user.name} section="orders"><Link className="back-link" href="/dashboard/orders">← My orders</Link><header className="page-heading split-heading"><div><span className="eyebrow">ORDER #{order.id.slice(0,8).toUpperCase()}</span><h1>Order details</h1><p>Placed {new Date(order.createdAt).toLocaleString("en-IN")}</p></div><span className={`commerce-status status-${order.status.toLowerCase()}`}>{order.status}</span></header><section className="panel order-detail-card"><div className="card-heading"><div><span className="eyebrow">DIGITAL ITEMS</span><h2>Your order</h2></div>{order.status==="PAID"?<Link className="button secondary" href={`/invoice/${order.id}`}>Download invoice</Link>:null}</div><div className="order-items">{order.items.map((item)=><article key={item.productId}><span className="order-item-icon">P</span><div><h3>{item.name}</h3><p>{item.accessDays} days digital access</p></div><strong>{formatMoney(item.pricePaise,order.currency)}</strong></article>)}</div></section><div className="order-detail-grid"><section className="panel"><span className="eyebrow">PAYMENT DETAILS</span><h2>{order.paymentStatus??"Payment pending"}</h2><dl className="detail-list"><div><dt>Payment method</dt><dd>{order.provider?order.provider.toUpperCase():"—"}</dd></div><div><dt>Transaction ID</dt><dd>{order.providerPaymentId??"—"}</dd></div><div><dt>Paid on</dt><dd>{order.paidAt?new Date(order.paidAt).toLocaleString("en-IN"):"—"}</dd></div></dl></section><section className="panel price-summary"><span className="eyebrow">PRICE SUMMARY</span><dl><div><dt>Subtotal</dt><dd>{formatMoney(order.subtotalPaise,order.currency)}</dd></div>{order.discountPaise>0?<div><dt>Coupon discount {order.couponCode?`(${order.couponCode})`:""}</dt><dd>− {formatMoney(order.discountPaise,order.currency)}</dd></div>:null}<div className="total"><dt>Total</dt><dd>{formatMoney(order.totalPaise,order.currency)}</dd></div></dl></section></div></WorkspaceShell>}
