import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentOrder } from "@/features/commerce/service";
import { commerceIdSchema } from "@/features/commerce/validation";
import { formatMoney } from "@/features/commerce/pricing";

type Order={id:string;status:string;subtotalPaise:number;discountPaise:number;taxPaise:number;totalPaise:number;currency:string;couponCode:string|null;createdAt:Date;paidAt:Date|null;provider:string|null;providerPaymentId:string|null;paymentStatus:string|null;items:{productId:string;name:string;pricePaise:number;accessDays:number}[]};
export const metadata={title:"Order details"};

export default async function Page({params}:{params:Promise<{id:string}>}){const auth=await requireWorkspace();if(auth.admin)redirect("/admin");const parsed=commerceIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const raw=await getStudentOrder(parsed.data,auth.user.id);if(!raw)notFound();const order=raw as unknown as Order;const paid=order.status==="PAID";return <WorkspaceShell admin={false} name={auth.user.name} section="orders"><nav className="student-breadcrumb"><Link href="/dashboard/courses">My Packages</Link><span>›</span><b>Order Details</b></nav><Link className="back-link" href="/dashboard/orders">← Back to My Orders</Link><header className="reference-order-header"><div><h1>Order #{order.id.slice(0,12).toUpperCase()}</h1><p>Placed on {new Date(order.createdAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</p></div><span className={`commerce-status status-${order.status.toLowerCase()}`}>● {order.status}</span>{paid?<Link className="button secondary" href={`/invoice/${order.id}`}>⇩ Download Invoice</Link>:null}</header><section className="reference-order-items"><div className="order-table-head"><b>Order Items</b><span>Price</span><span>Qty</span><span>Amount</span></div>{order.items.map(item=><article key={item.productId}><i>PS</i><div><h2>{item.name}</h2><p>Study Materials&nbsp; • &nbsp;Tests &amp; Practice&nbsp; • &nbsp;Results &amp; Analytics</p><small>Valid for {item.accessDays} days from purchase</small></div><strong>{formatMoney(item.pricePaise,order.currency)}</strong><span>1</span><b>{formatMoney(item.pricePaise,order.currency)}</b></article>)}</section><div className="order-detail-grid reference-order-grid"><section><h2>Payment Details</h2><dl className="detail-list"><div><dt>Payment Method</dt><dd>{order.provider?order.provider.toUpperCase():"Pending"}</dd></div><div><dt>Payment Status</dt><dd><span className={`commerce-status status-${order.status.toLowerCase()}`}>● {order.paymentStatus??order.status}</span></dd></div><div><dt>Transaction ID</dt><dd>{order.providerPaymentId??"—"}</dd></div><div><dt>Paid on</dt><dd>{order.paidAt?new Date(order.paidAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—"}</dd></div></dl></section><section className="price-summary"><h2>Price Summary</h2><dl><div><dt>Subtotal</dt><dd>{formatMoney(order.subtotalPaise,order.currency)}</dd></div>{order.discountPaise>0?<div><dt>Coupon discount {order.couponCode?`(${order.couponCode})`:""}</dt><dd>− {formatMoney(order.discountPaise,order.currency)}</dd></div>:null}<div><dt>GST (18%)</dt><dd>{formatMoney(order.taxPaise,order.currency)}</dd></div><div className="total"><dt>Total Amount {paid?"Paid":"Due"}</dt><dd>{formatMoney(order.totalPaise,order.currency)}</dd></div></dl><p className={paid?"payment-success-note":"payment-pending-note"}>{paid?"✓ Payment completed successfully. A tax invoice has been generated for this order.":"Payment is pending for this order."}</p></section></div></WorkspaceShell>;}
