"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Field } from "@/features/auth/ui/field";
import type { ApiFailure, ApiSuccess } from "@/lib/http/api-response";

type Exam = { id: string; name: string };
type TestDetails = { id: string; examId: string; title: string; mode: "PRACTICE" | "MOCK" | "LIVE"; durationMinutes: number; instructions: string | null; maxAttempts: number; shuffleQuestions: boolean; shuffleOptions: boolean; status: string };
type Section = { id: string; title: string; sortOrder: number; questions: { questionId: string; stem: string; type: string; sortOrder: number }[] };
type Question = { id: string; stem: string; topicName: string; subjectName: string };

class RequestError extends Error {}
async function request<T>(path: string, method: "POST" | "PATCH", body: Record<string, unknown>) {
  const response = await fetch(`/api/admin/tests/${path}`, { method, credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const payload = await response.json() as ApiSuccess<T> | ApiFailure;
  if (!response.ok || "error" in payload) throw new RequestError("error" in payload ? payload.error.message : "Couldn't complete this request.");
  return payload.data;
}
function payload(data: FormData) { return { examId: String(data.get("examId")), title: String(data.get("title")), mode: String(data.get("mode")), durationMinutes: Number(data.get("durationMinutes")), instructions: String(data.get("instructions") ?? ""), maxAttempts: Number(data.get("maxAttempts")), shuffleQuestions: data.get("shuffleQuestions") === "on", shuffleOptions: data.get("shuffleOptions") === "on" }; }

export function TestCreateForm({ exams }: { exams: Exam[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const result = await request<{ id: string }>("", "POST", payload(new FormData(event.currentTarget))); router.push(`/admin/tests/${result.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Couldn't create the test."); setBusy(false); } }
  return <form className="admin-form" onSubmit={submit}><fieldset disabled={busy}><label className="field"><span>Exam</span><select name="examId" required>{exams.map((exam) => <option value={exam.id} key={exam.id}>{exam.name}</option>)}</select></label><Field id="new-test-title" label="Test title" name="title" required minLength={3} maxLength={200} placeholder="Full-length mock test 01" /><div className="question-grid"><label className="field"><span>Mode</span><select name="mode" defaultValue="MOCK"><option value="PRACTICE">Practice</option><option value="MOCK">Mock</option><option value="LIVE">Live</option></select></label><Field id="new-test-duration" label="Duration (minutes)" name="durationMinutes" type="number" min={1} max={600} defaultValue={60} required /></div><Field id="new-test-attempts" label="Maximum attempts" name="maxAttempts" type="number" min={1} max={100} defaultValue={1} required /><label className="check-row"><input name="shuffleQuestions" type="checkbox" defaultChecked /> Shuffle questions</label><label className="check-row"><input name="shuffleOptions" type="checkbox" defaultChecked /> Shuffle options</label><label className="field"><span>Instructions</span><textarea name="instructions" maxLength={10000} rows={4} /></label><button className="button" type="submit">{busy ? "Creating…" : "Create draft test"}</button></fieldset>{error && <p className="notice danger" role="alert">{error}</p>}</form>;
}

export function TestBuilder({ test, exams, sections, questions, canManage, canSchedule }: { test: TestDetails; exams: Exam[]; sections: Section[]; questions: Question[]; canManage: boolean; canSchedule: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const draft = test.status === "DRAFT" && canManage;
  async function mutate(event: FormEvent<HTMLFormElement>, path: string, method: "POST" | "PATCH", bodyBuilder: (data: FormData) => Record<string, unknown>, key: string) { event.preventDefault(); setBusy(key); setError(""); try { await request(path, method, bodyBuilder(new FormData(event.currentTarget))); if (method === "POST") event.currentTarget.reset(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Couldn't save this change."); } finally { setBusy(""); } }
  async function publish() { setBusy("publish"); setError(""); try { await request(`${test.id}/publish`, "POST", {}); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Couldn't publish the test."); } finally { setBusy(""); } }
  return <div className="test-builder">
    {draft && <section className="panel"><span className="eyebrow">CONFIGURATION</span><h2>Test settings</h2><form className="admin-form" onSubmit={(event) => mutate(event, test.id, "PATCH", payload, "settings")}><fieldset disabled={Boolean(busy)}><label className="field"><span>Exam</span><select name="examId" defaultValue={test.examId}>{exams.map((exam) => <option value={exam.id} key={exam.id}>{exam.name}</option>)}</select></label><Field id="edit-test-title" label="Title" name="title" defaultValue={test.title} required /><div className="question-grid"><label className="field"><span>Mode</span><select name="mode" defaultValue={test.mode}><option value="PRACTICE">Practice</option><option value="MOCK">Mock</option><option value="LIVE">Live</option></select></label><Field id="edit-test-duration" label="Duration" name="durationMinutes" type="number" min={1} max={600} defaultValue={test.durationMinutes} required /></div><Field id="edit-test-attempts" label="Maximum attempts" name="maxAttempts" type="number" min={1} max={100} defaultValue={test.maxAttempts} required /><label className="check-row"><input name="shuffleQuestions" type="checkbox" defaultChecked={test.shuffleQuestions} /> Shuffle questions</label><label className="check-row"><input name="shuffleOptions" type="checkbox" defaultChecked={test.shuffleOptions} /> Shuffle options</label><label className="field"><span>Instructions</span><textarea name="instructions" defaultValue={test.instructions ?? ""} rows={4} /></label><button className="button secondary" type="submit">{busy === "settings" ? "Saving…" : "Save settings"}</button></fieldset></form></section>}
    <section><div className="section-heading"><div><span className="eyebrow">PAPER STRUCTURE</span><h2>Sections and questions</h2></div>{draft && <button type="button" className="button" disabled={Boolean(busy)} onClick={publish}>{busy === "publish" ? "Publishing…" : "Publish test"}</button>}</div>{sections.length ? <div className="taxonomy-list">{sections.map((section) => <article className="taxonomy-card" key={section.id}><h3>{section.title}</h3><p className="muted">{section.questions.length} questions · order {section.sortOrder}</p>{section.questions.map((question) => <div className="assigned-question" key={question.questionId}><span>{question.sortOrder + 1}</span><p>{question.stem}</p><small>{question.type.replaceAll("_", " ")}</small></div>)}{draft && questions.length > 0 && <form className="topic-row topic-new" onSubmit={(event) => mutate(event, `sections/${section.id}/questions`, "POST", (data) => ({ questionId: String(data.get("questionId")), sortOrder: Number(data.get("sortOrder")) }), `assign-${section.id}`)}><fieldset disabled={Boolean(busy)}><label className="field"><span>Published question</span><select name="questionId">{questions.map((question) => <option value={question.id} key={question.id}>{question.subjectName} · {question.topicName} · {question.stem.slice(0, 70)}</option>)}</select></label><Field id={`assign-order-${section.id}`} label="Order" name="sortOrder" type="number" min={0} defaultValue={section.questions.length} required /><button className="button" type="submit">Assign</button></fieldset></form>}</article>)}</div> : <div className="panel empty-state compact-empty"><h2>No sections yet</h2><p>Add a section to start building the paper.</p></div>}
      {draft && <form className="panel inline-admin-form" onSubmit={(event) => mutate(event, `${test.id}/sections`, "POST", (data) => ({ title: String(data.get("title")), durationMinutes: data.get("durationMinutes") ? Number(data.get("durationMinutes")) : null, sortOrder: Number(data.get("sortOrder")) }), "section")}><fieldset disabled={Boolean(busy)}><Field id="new-section-title" label="New section" name="title" required /><div className="question-grid"><Field id="new-section-duration" label="Section minutes (optional)" name="durationMinutes" type="number" min={1} max={600} /><Field id="new-section-order" label="Order" name="sortOrder" type="number" min={0} defaultValue={sections.length} required /></div><button className="button secondary" type="submit">{busy === "section" ? "Adding…" : "Add section"}</button></fieldset></form>}</section>
    {test.mode === "LIVE" && test.status === "PUBLISHED" && canSchedule && <section className="panel"><span className="eyebrow">LIVE WINDOW</span><h2>Add schedule</h2><form className="admin-form" onSubmit={(event) => mutate(event, `${test.id}/schedules`, "POST", (data) => ({ startsAt: new Date(String(data.get("startsAt"))).toISOString(), endsAt: new Date(String(data.get("endsAt"))).toISOString(), resultReleaseAt: data.get("resultReleaseAt") ? new Date(String(data.get("resultReleaseAt"))).toISOString() : null, lateJoinMinutes: Number(data.get("lateJoinMinutes")), rankingEnabled: data.get("rankingEnabled") === "on", cohortKey: String(data.get("cohortKey") ?? "") }), "schedule")}><fieldset disabled={Boolean(busy)}><div className="question-grid"><Field id="schedule-start" label="Starts at" name="startsAt" type="datetime-local" required /><Field id="schedule-end" label="Ends at" name="endsAt" type="datetime-local" required /></div><div className="question-grid"><Field id="schedule-release" label="Result release" name="resultReleaseAt" type="datetime-local" /><Field id="schedule-late" label="Late join (minutes)" name="lateJoinMinutes" type="number" min={0} max={180} defaultValue={15} required /></div><Field id="schedule-cohort" label="Cohort key (optional)" name="cohortKey" maxLength={100} /><label className="check-row"><input name="rankingEnabled" type="checkbox" /> Enable ranking</label><button className="button" type="submit">{busy === "schedule" ? "Scheduling…" : "Add live schedule"}</button></fieldset></form></section>}
    {error && <p className="notice danger" role="alert">{error}</p>}
  </div>;
}
