import Link from "next/link";
import { listAvailableProducts } from "@/features/catalog/repository";
export const dynamic = "force-dynamic";
export const metadata = { title: "All packages" };
const formatPrice = (paise: number) => paise === 0 ? "Free" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;price?:string;format?:string}>}) {
  const query = await searchParams;
  const q = query.q?.trim().toLowerCase() ?? "";
  const price = query.price ?? "all";
  const format = query.format ?? "all";
  const all = await listAvailableProducts();
  const rows = all.filter((product) => (!q || `${product.name} ${product.description ?? ""}`.toLowerCase().includes(q)) && (price === "free" ? product.pricePaise === 0 : price === "under1000" ? product.pricePaise > 0 && product.pricePaise <= 100000 : price === "under5000" ? product.pricePaise <= 500000 : true) && (format === "tests" ? product.testCount > 0 : format === "materials" ? product.materialCount > 0 : true));
  return <main className="public-main catalogue-page"><header className="listing-heading"><span className="eyebrow">ALL PACKAGES</span><h1>Find the right preparation package</h1><p>Search and compare digital packages by included tests, study materials, access duration and price.</p></header><form className="catalogue-filters"><label className="catalogue-search"><span className="sr-only">Search</span><input name="q" defaultValue={query.q} placeholder="Search exams or packages" /></label><label><span>Price</span><select name="price" defaultValue={price}><option value="all">All prices</option><option value="free">Free</option><option value="under1000">Under ₹1,000</option><option value="under5000">Under ₹5,000</option></select></label><label><span>Includes</span><select name="format" defaultValue={format}><option value="all">All formats</option><option value="tests">Tests & practice</option><option value="materials">Study materials</option></select></label><button className="button" type="submit">Apply filters</button>{q || price !== "all" || format !== "all" ? <Link className="button secondary" href="/packages">Clear</Link> : null}</form><div className="catalogue-count"><span>{rows.length} package{rows.length === 1 ? "" : "s"}</span><small>Digital access only</small></div>{rows.length ? <div className="catalog-grid">{rows.map((product, index) => {const discount = product.mrpPaise && product.mrpPaise > product.pricePaise ? Math.round((1-product.pricePaise/product.mrpPaise)*100) : 0;return <Link className="exam-card" href={`/packages/${product.slug}`} key={product.id}><div className={`product-cover cover-${index % 4}`}><span>{index === 0 ? "Bestseller" : "Exam package"}</span><b>{product.name.slice(0,2).toUpperCase()}</b></div><div className="catalog-card-body"><small>{product.testCount} tests · {product.materialCount} materials</small><h2>{product.name}</h2><p>{product.description || "Study materials and exam-focused practice in one package."}</p><div className="catalog-price"><strong>{formatPrice(product.pricePaise)}</strong>{product.mrpPaise && product.mrpPaise > product.pricePaise ? <><del>{formatPrice(product.mrpPaise)}</del><span>{discount}% off</span></> : null}</div><span className="card-meta">{product.accessDays} days access <b aria-hidden="true">View package →</b></span></div></Link>;})}</div> : <section className="panel empty-state"><span className="eyebrow">NO MATCH</span><h2>No packages match these filters</h2><p>Try a different search or clear the active filters.</p><Link className="button secondary" href="/packages">Clear filters</Link></section>}</main>;
}
