/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */
"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { StorefrontProductCard, type StorefrontProduct } from "@/components/storefront-product-card";
import { formatMoney } from "../pricing";
import { commerceRequest, CommerceApiError } from "./api";

const storageKey="prepstore-cart";
export type CartProduct={id:string;slug:string;name:string;description:string|null;coverObjectKey:string|null;mrpPaise:number|null;pricePaise:number;currency:string;accessDays:number};
type Preview={products:CartProduct[];subtotalPaise:number;discountPaise:number;taxPaise:number;totalPaise:number;currency:string;couponCode:string|null};
type Checkout=Preview&{id:string;status:string;paymentRequired:boolean;paymentAttemptId:string|null;checkoutReference:string|null};
type Account={name:string;email:string;phone:string|null};

export function readCart(){if(typeof window==="undefined")return[] as string[];try{const value=JSON.parse(localStorage.getItem(storageKey)??"[]");return Array.isArray(value)?value.filter((id):id is string=>typeof id==="string").slice(0,20):[];}catch{return[];}}
export function addCartItem(id:string){const ids=[...new Set([...readCart(),id])];localStorage.setItem(storageKey,JSON.stringify(ids));window.dispatchEvent(new Event("prepstore-cart"));return ids.length;}
export function clearCart(){localStorage.removeItem(storageKey);window.dispatchEvent(new Event("prepstore-cart"));}
function removeCartItem(id:string){localStorage.setItem(storageKey,JSON.stringify(readCart().filter(item=>item!==id)));window.dispatchEvent(new Event("prepstore-cart"));}
async function loadProducts(ids:string[]){if(!ids.length)return[];const query=ids.map(id=>`id=${encodeURIComponent(id)}`).join("&");const response=await fetch(`/api/catalog/cart?${query}`,{credentials:"same-origin"});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message??"Couldn't load your cart.");return result.data as CartProduct[];}
const localPreview=(products:CartProduct[]):Preview=>{const subtotalPaise=products.reduce((sum,item)=>sum+item.pricePaise,0);const taxPaise=Math.floor(subtotalPaise*.18);return{products,subtotalPaise,discountPaise:0,taxPaise,totalPaise:subtotalPaise+taxPaise,currency:products[0]?.currency??"INR",couponCode:null}};

export function CartCount(){const[count,setCount]=useState(0);useEffect(()=>{const update=()=>setCount(readCart().length);update();window.addEventListener("prepstore-cart",update);return()=>window.removeEventListener("prepstore-cart",update);},[]);return <span className="cart-count" aria-label={`${count} products in cart`}>{count}</span>;}
export function AddToCartButton({productId,className="button secondary full"}:{productId:string;className?:string}){const[added,setAdded]=useState(false);return <button type="button" className={className} onClick={()=>{addCartItem(productId);setAdded(true);}}>{added?"Added to cart":"Add to cart"}</button>;}

function ProductRows({products,onRemove,compact=false}:{products:CartProduct[];onRemove?:(id:string)=>void;compact?:boolean}){return <div className={compact?"cart-product-list compact":"cart-product-list"}>{products.map(product=>{const discount=product.mrpPaise&&product.mrpPaise>product.pricePaise?Math.round((1-product.pricePaise/product.mrpPaise)*100):0;return <article key={product.id}><div className="cart-cover">{product.coverObjectKey?<img src={`/api/catalog/products/${product.id}/cover`} alt=""/>:<b>{product.name.slice(0,2).toUpperCase()}</b>}</div><div className="cart-item-copy"><Link href={`/packages/${product.slug}`}><h2>{product.name}</h2></Link><p>{Math.max(1,Math.round(product.accessDays/30))} months access <i/> Digital package</p><div className="cart-item-price"><strong>{formatMoney(product.pricePaise,product.currency)}</strong>{product.mrpPaise&&product.mrpPaise>product.pricePaise?<del>{formatMoney(product.mrpPaise,product.currency)}</del>:null}{discount>0?<span>{discount}% OFF</span>:null}</div></div>{onRemove?<button type="button" className="cart-remove" onClick={()=>onRemove(product.id)}><span aria-hidden="true">♲</span> Remove</button>:<strong>{formatMoney(product.pricePaise,product.currency)}</strong>}</article>})}</div>}

function PriceSummary({preview,itemCount}:{preview:Preview;itemCount:number}){return <dl className="commerce-price-summary"><div><dt>Subtotal ({itemCount} item{itemCount===1?"":"s"})</dt><dd>{formatMoney(preview.subtotalPaise,preview.currency)}</dd></div>{preview.discountPaise>0?<div className="discount"><dt>Coupon discount</dt><dd>− {formatMoney(preview.discountPaise,preview.currency)}</dd></div>:null}<div><dt>Taxable value</dt><dd>{formatMoney(preview.subtotalPaise-preview.discountPaise,preview.currency)}</dd></div><div><dt>GST (18%)</dt><dd>{formatMoney(preview.taxPaise,preview.currency)}</dd></div><div className="total"><dt>Total payable</dt><dd>{formatMoney(preview.totalPaise,preview.currency)}</dd></div></dl>}

export function CartPageClient({suggestions}:{suggestions:StorefrontProduct[]}){
  const[products,setProducts]=useState<CartProduct[]>([]);const[preview,setPreview]=useState<Preview|null>(null);const[coupon,setCoupon]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function refresh(){setLoading(true);try{const items=await loadProducts(readCart());setProducts(items);setPreview(localPreview(items));setError("");}catch(value){setError(value instanceof Error?value.message:"Couldn't load your cart.");}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]);
  async function applyCoupon(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:products.map(item=>item.id),couponCode:coupon}));}catch(value){const issue=value as CommerceApiError;setError(issue.code==="UNAUTHENTICATED"?"Sign in at checkout to validate and use this coupon.":issue.message);}finally{setBusy(false);}}
  const recommended=suggestions.filter(item=>!products.some(product=>product.id===item.id)).slice(0,3);
  return <><nav className="store-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><b>Your cart</b></nav><div className="reference-cart-layout"><section><header className="reference-commerce-heading"><h1>Your cart</h1><p>{products.length} item{products.length===1?"":"s"} in your cart</p></header>{loading?<p>Loading cart…</p>:products.length?<><ProductRows products={products} onRemove={id=>{removeCartItem(id);void refresh();}}/><form className="cart-coupon" onSubmit={applyCoupon}><label htmlFor="cart-coupon">Apply coupon code</label><div><input id="cart-coupon" value={coupon} onChange={event=>setCoupon(event.target.value.toUpperCase())} placeholder="Enter coupon code" maxLength={60}/><button disabled={!coupon.trim()||busy}>{busy?"Applying…":"Apply"}</button></div></form><Link className="continue-browsing" href="/packages">← <span>Continue browsing</span></Link></>:<section className="panel empty-state"><h2>Your cart is empty</h2><p>Explore Prepstore packages and add the preparation you need.</p><Link className="button" href="/packages">Explore packages</Link></section>}{error?<p className="notice danger" role="alert">{error}</p>:null}</section>{products.length>0&&preview?<aside className="reference-order-summary"><h2>Order summary</h2><PriceSummary preview={preview} itemCount={products.length}/><Link className="reference-checkout-button" href={preview.couponCode?`/checkout?coupon=${encodeURIComponent(preview.couponCode)}`:"/checkout"}>Proceed to checkout</Link><p>▣ <span>Secure &amp; safe payment powered by trusted partners</span></p></aside>:null}</div>{recommended.length?<section className="cart-recommendations"><header><h2>You may also like</h2><Link href="/packages">View all <span>→</span></Link></header><div>{recommended.map((item,index)=><StorefrontProductCard key={item.id} product={item} index={index+2} variant="catalog"/>)}</div></section>:null}</>;
}

export function CheckoutPageClient({account,initialCoupon=""}:{account:Account|null;initialCoupon?:string}){
  const router=useRouter();const key=useRef("");const initialCouponRef=useRef(initialCoupon);const accountRef=useRef(account);const[products,setProducts]=useState<CartProduct[]>([]);const[preview,setPreview]=useState<Preview|null>(null);const[coupon,setCoupon]=useState(initialCoupon);const[busy,setBusy]=useState("");const[error,setError]=useState("");
  async function refresh(code:string|null=null){const ids=readCart();if(!ids.length){setProducts([]);return;}try{const items=await loadProducts(ids);setProducts(items);if(account)setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:ids,couponCode:code}));else setPreview(localPreview(items));}catch(value){const issue=value as CommerceApiError;setError(issue.message);}}
  useEffect(()=>{const initialize=async()=>{const ids=readCart();if(!ids.length)return;try{const items=await loadProducts(ids);setProducts(items);if(accountRef.current)setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:ids,couponCode:initialCouponRef.current||null}));else setPreview(localPreview(items));}catch(value){const issue=value as CommerceApiError;setError(issue.message);}};void initialize();},[]);
  async function apply(event:FormEvent){event.preventDefault();setBusy("coupon");setError("");await refresh(coupon);setBusy("");}
  async function placeOrder(){setBusy("order");setError("");try{key.current||=crypto.randomUUID();const result=await commerceRequest<Checkout>("commerce/checkout",{productIds:readCart(),couponCode:preview?.couponCode,idempotencyKey:key.current});if(!result.paymentRequired){clearCart();router.push(`/invoice/${result.id}`);}else if(result.checkoutReference?.startsWith("/"))router.push(result.checkoutReference);else if(result.checkoutReference)window.location.assign(result.checkoutReference);else router.push(`/dashboard/orders/${result.id}`);}catch(value){const issue=value as CommerceApiError;setError(issue.message);}finally{setBusy("");}}
  if(!products.length&&!error)return <section className="panel empty-state"><h1>Your cart is empty</h1><Link className="button" href="/packages">Explore packages</Link></section>;
  return <><nav className="store-breadcrumb" aria-label="Breadcrumb"><Link href="/cart">Cart</Link><span>›</span><b>Checkout</b></nav><header className="reference-commerce-heading"><h1>Checkout</h1><p>Complete your purchase to get instant access to your selected packages.</p></header><div className="reference-checkout-layout"><section className="reference-billing-card"><h2>Billing details</h2><p>Your account details are prefilled.</p>{account?<div className="billing-fields"><label>Full name<input value={account.name} readOnly/></label><label>Email address<input value={account.email} readOnly/></label><label>Phone number<input value={account.phone??"Not added to your profile"} readOnly/></label></div>:<div className="signin-required"><p>Sign in to use your verified account details and place this order.</p><Link className="reference-checkout-button" href="/login?next=%2Fcheckout">Sign in to place order</Link></div>}</section><aside className="reference-checkout-summary"><h2>Order summary</h2><ProductRows products={products} compact/><form className="checkout-coupon" onSubmit={apply}><input value={coupon} onChange={event=>setCoupon(event.target.value.toUpperCase())} placeholder="Coupon code"/><button disabled={!account||!coupon.trim()||Boolean(busy)}>{busy==="coupon"?"Applying…":"Apply"}</button></form>{preview?<PriceSummary preview={preview} itemCount={products.length}/>:null}<div className="secure-payment">▣ <span><b>Secure payment powered by Razorpay</b><small>Your payment information is encrypted and secure.</small></span></div><button className="reference-checkout-button" disabled={!account||Boolean(busy)} onClick={placeOrder}>{busy==="order"?"Creating order…":`Place order & pay${preview?` ${formatMoney(preview.totalPaise,preview.currency)}`:""} →`}</button>{error?<p className="notice danger" role="alert">{error}</p>:null}</aside></div></>;
}

export function ClearCartOnMount(){useEffect(()=>clearCart(),[]);return null;}
