/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useRef, useState, useSyncExternalStore, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { StorefrontProductCard, type StorefrontProduct } from "@/components/storefront-product-card";
import { formatMoney } from "../pricing";
import { commerceRequest, CommerceApiError } from "./api";
import { formatAccessDuration } from "@/features/catalog/presentation";

const storageKey="prepstore-cart";
const cartEvent="prepstore-cart";
export type CartProduct={id:string;slug:string;name:string;description:string|null;coverObjectKey:string|null;mrpPaise:number|null;pricePaise:number;currency:string;accessDays:number};
type Preview={products:CartProduct[];subtotalPaise:number;discountPaise:number;taxPaise:number;totalPaise:number;currency:string;couponCode:string|null};
type Checkout=Preview&{id:string;status:string;paymentRequired:boolean;paymentAttemptId:string|null;checkoutReference:string|null};
type Account={name:string;email:string;phone:string|null};

export function readCart(){if(typeof window==="undefined")return[] as string[];try{const value=JSON.parse(localStorage.getItem(storageKey)??"[]");return Array.isArray(value)?value.filter((id):id is string=>typeof id==="string").slice(0,20):[];}catch{return[];}}
function writeCart(ids:string[]){localStorage.setItem(storageKey,JSON.stringify(ids));window.dispatchEvent(new Event(cartEvent));return ids;}
function cartSnapshot(){return readCart().join(",");}
function serverCartSnapshot(){return "";}
function subscribeCart(onStoreChange:()=>void){window.addEventListener(cartEvent,onStoreChange);const onStorage=(event:StorageEvent)=>{if(event.key===storageKey)onStoreChange();};window.addEventListener("storage",onStorage);return()=>{window.removeEventListener(cartEvent,onStoreChange);window.removeEventListener("storage",onStorage);};}
function useCartIds(){const value=useSyncExternalStore(subscribeCart,cartSnapshot,serverCartSnapshot);return useMemo(()=>value?value.split(","):[],[value]);}
function useCartHydrated(){const[hydrated,setHydrated]=useState(false);useEffect(()=>setHydrated(true),[]);return hydrated;}
export function addCartItem(id:string){return writeCart([...new Set([...readCart(),id])]).length;}
export function clearCart(){localStorage.removeItem(storageKey);window.dispatchEvent(new Event(cartEvent));}
function removeCartItem(id:string){writeCart(readCart().filter(item=>item!==id));}
function reconcileCart(requestedIds:string[],products:CartProduct[]){const valid=new Set(products.map(product=>product.id));const next=requestedIds.filter(id=>valid.has(id));if(next.join(",")!==requestedIds.join(","))writeCart(next);return next;}
async function loadProducts(ids:string[],signal?:AbortSignal){if(!ids.length)return[];const query=ids.map(id=>`id=${encodeURIComponent(id)}`).join("&");const response=await fetch(`/api/catalog/cart?${query}`,{credentials:"same-origin",cache:"no-store",signal});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message??"Couldn't load your cart.");if(!Array.isArray(result?.data))throw new Error("The cart response was invalid. Please refresh and try again.");return result.data as CartProduct[];}
const localPreview=(products:CartProduct[]):Preview=>{const subtotalPaise=products.reduce((sum,item)=>sum+item.pricePaise,0);const taxPaise=Math.floor(subtotalPaise*.18);return{products,subtotalPaise,discountPaise:0,taxPaise,totalPaise:subtotalPaise+taxPaise,currency:products[0]?.currency??"INR",couponCode:null}};
function TrashIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>}

export function CartCount(){const ids=useCartIds();const hydrated=useCartHydrated();useEffect(()=>{if(!hydrated||!ids.length)return;const controller=new AbortController();void loadProducts(ids,controller.signal).then(products=>reconcileCart(ids,products)).catch(error=>{if(!(error instanceof DOMException&&error.name==="AbortError"))return;});return()=>controller.abort();},[hydrated,ids]);return <span className="cart-count" aria-label={`${hydrated?ids.length:0} products in cart`}>{hydrated?ids.length:0}</span>;}
export function AddToCartButton({productId,className="button secondary full"}:{productId:string;className?:string}){const ids=useCartIds();const added=ids.includes(productId);return <button type="button" className={className} onClick={()=>addCartItem(productId)}>{added?"Added to cart":"Add to cart"}</button>;}

function ProductRows({products,onRemove,compact=false}:{products:CartProduct[];onRemove?:(id:string)=>void;compact?:boolean}){return <div className={compact?"cart-product-list compact":"cart-product-list"}>{products.map(product=>{const discount=product.mrpPaise&&product.mrpPaise>product.pricePaise?Math.round((1-product.pricePaise/product.mrpPaise)*100):0;return <article key={product.id}><div className="cart-cover">{product.coverObjectKey?<Image src={`/api/catalog/products/${product.id}/cover`} alt={`${product.name} cover`} fill sizes={compact?"56px":"112px"}/>:<b>{product.name.slice(0,2).toUpperCase()}</b>}</div><div className="cart-item-copy"><Link href={`/packages/${product.slug}`}><h2>{product.name}</h2></Link><p>{formatAccessDuration(product.accessDays)} access <i/> Digital package</p><div className="cart-item-price"><strong>{formatMoney(product.pricePaise,product.currency)}</strong>{product.mrpPaise&&product.mrpPaise>product.pricePaise?<del>{formatMoney(product.mrpPaise,product.currency)}</del>:null}{discount>0?<span>{discount}% OFF</span>:null}</div></div>{onRemove?<button type="button" className="cart-remove" aria-label={`Remove ${product.name} from cart`} onClick={()=>onRemove(product.id)}><TrashIcon/> Remove</button>:<strong>{formatMoney(product.pricePaise,product.currency)}</strong>}</article>})}</div>}

function PriceSummary({preview,itemCount}:{preview:Preview;itemCount:number}){return <dl className="commerce-price-summary"><div><dt>Subtotal ({itemCount} item{itemCount===1?"":"s"})</dt><dd>{formatMoney(preview.subtotalPaise,preview.currency)}</dd></div>{preview.discountPaise>0?<div className="discount"><dt>Coupon discount</dt><dd>− {formatMoney(preview.discountPaise,preview.currency)}</dd></div>:null}<div><dt>Taxable value</dt><dd>{formatMoney(preview.subtotalPaise-preview.discountPaise,preview.currency)}</dd></div><div><dt>GST (18%)</dt><dd>{formatMoney(preview.taxPaise,preview.currency)}</dd></div><div className="total"><dt>Total payable</dt><dd>{formatMoney(preview.totalPaise,preview.currency)}</dd></div></dl>}

export function CartPageClient({suggestions}:{suggestions:StorefrontProduct[]}){
  const cartIds=useCartIds();
  const hydrated=useCartHydrated();
  const[products,setProducts]=useState<CartProduct[]>([]);const[preview,setPreview]=useState<Preview|null>(null);const[coupon,setCoupon]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{if(!hydrated)return;const controller=new AbortController();setLoading(true);void loadProducts(cartIds,controller.signal).then(items=>{reconcileCart(cartIds,items);setProducts(items);setPreview(localPreview(items));setError("");}).catch(value=>{if(value instanceof DOMException&&value.name==="AbortError")return;setError(value instanceof Error?value.message:"Couldn't load your cart.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[hydrated,cartIds]);
  async function applyCoupon(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:products.map(item=>item.id),couponCode:coupon}));}catch(value){const issue=value as CommerceApiError;setError(issue.code==="UNAUTHENTICATED"?"Sign in at checkout to validate and use this coupon.":issue.message);}finally{setBusy(false);}}
  const recommended=suggestions.filter(item=>!products.some(product=>product.id===item.id)).slice(0,3);
  return <><nav className="store-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><b>Your cart</b></nav><div className="reference-cart-layout"><section><header className="reference-commerce-heading"><h1>Your cart</h1><p>{products.length} item{products.length===1?"":"s"} in your cart</p></header>{loading?<p>Loading cart…</p>:products.length?<><ProductRows products={products} onRemove={removeCartItem}/><form className="cart-coupon" onSubmit={applyCoupon}><label htmlFor="cart-coupon">Apply coupon code</label><div><input id="cart-coupon" value={coupon} onChange={event=>setCoupon(event.target.value.toUpperCase())} placeholder="Enter coupon code" maxLength={60}/><button disabled={!coupon.trim()||busy}>{busy?"Applying…":"Apply"}</button></div></form><Link className="continue-browsing" href="/packages">← <span>Continue browsing</span></Link></>:<section className="panel empty-state"><h2>Your cart is empty</h2><p>Explore Prepstore packages and add the preparation you need.</p><Link className="button" href="/packages">Explore packages</Link></section>}{error?<p className="notice danger" role="alert">{error}</p>:null}</section>{products.length>0&&preview?<aside className="reference-order-summary"><h2>Order summary</h2><PriceSummary preview={preview} itemCount={products.length}/><Link className="reference-checkout-button" href={preview.couponCode?`/checkout?coupon=${encodeURIComponent(preview.couponCode)}`:"/checkout"}>Proceed to checkout</Link><p>▣ <span>Secure &amp; safe payment powered by trusted partners</span></p></aside>:null}</div>{recommended.length?<section className="cart-recommendations"><header><h2>You may also like</h2><Link href="/packages">View all <span>→</span></Link></header><div>{recommended.map((item,index)=><StorefrontProductCard key={item.id} product={item} index={index+2} variant="catalog"/>)}</div></section>:null}</>;
}

export function CheckoutPageClient({account,initialCoupon=""}:{account:Account|null;initialCoupon?:string}){
  const cartIds=useCartIds();const hydrated=useCartHydrated();const router=useRouter();const key=useRef("");const initialCouponRef=useRef(initialCoupon);const accountRef=useRef(account);const[products,setProducts]=useState<CartProduct[]>([]);const[preview,setPreview]=useState<Preview|null>(null);const[coupon,setCoupon]=useState(initialCoupon);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
  async function refresh(code:string|null=null){const ids=readCart();if(!ids.length){setProducts([]);setPreview(null);return;}try{const items=await loadProducts(ids);const validIds=reconcileCart(ids,items);setProducts(items);if(account)setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:validIds,couponCode:code}));else setPreview(localPreview(items));setError("");}catch(value){const issue=value as CommerceApiError;setError(issue.message);}}
  useEffect(()=>{if(!hydrated)return;const controller=new AbortController();const initialize=async()=>{setLoading(true);if(!cartIds.length){setProducts([]);setPreview(null);setLoading(false);return;}try{const items=await loadProducts(cartIds,controller.signal);if(controller.signal.aborted)return;const validIds=reconcileCart(cartIds,items);setProducts(items);if(accountRef.current)setPreview(await commerceRequest<Preview>("commerce/checkout/preview",{productIds:validIds,couponCode:initialCouponRef.current||null}));else setPreview(localPreview(items));setError("");}catch(value){if(value instanceof DOMException&&value.name==="AbortError")return;const issue=value as CommerceApiError;setError(issue.message);}finally{if(!controller.signal.aborted)setLoading(false);}};void initialize();return()=>controller.abort();},[hydrated,cartIds]);
  async function apply(event:FormEvent){event.preventDefault();setBusy("coupon");setError("");await refresh(coupon);setBusy("");}
  async function placeOrder(){setBusy("order");setError("");try{key.current||=crypto.randomUUID();const result=await commerceRequest<Checkout>("commerce/checkout",{productIds:readCart(),couponCode:preview?.couponCode,idempotencyKey:key.current});if(!result.paymentRequired){clearCart();router.push(`/invoice/${result.id}`);}else if(result.checkoutReference?.startsWith("/"))router.push(result.checkoutReference);else if(result.checkoutReference)window.location.assign(result.checkoutReference);else router.push(`/dashboard/orders/${result.id}`);}catch(value){const issue=value as CommerceApiError;setError(issue.message);}finally{setBusy("");}}
  if(loading)return <section className="panel empty-state" aria-live="polite"><div className="checkout-loading" aria-hidden="true"/><h1>Preparing checkout…</h1><p>We’re confirming your cart and current price.</p></section>;
  if(!products.length&&!error)return <section className="panel empty-state"><h1>Your cart is empty</h1><Link className="button" href="/packages">Explore packages</Link></section>;
  return <><nav className="store-breadcrumb" aria-label="Breadcrumb"><Link href="/cart">Cart</Link><span>›</span><b>Checkout</b></nav><header className="reference-commerce-heading"><h1>Checkout</h1><p>Complete your purchase to get instant access to your selected packages.</p></header><div className="reference-checkout-layout"><section className="reference-billing-card"><h2>Billing details</h2><p>Your account details are prefilled.</p>{account?<div className="billing-fields"><label>Full name<input value={account.name} readOnly/></label><label>Email address<input value={account.email} readOnly/></label><label>Phone number<input value={account.phone??"Not added to your profile"} readOnly/></label></div>:<div className="signin-required"><p>Sign in to use your verified account details and place this order.</p><Link className="reference-checkout-button" href="/login?next=%2Fcheckout">Sign in to place order</Link></div>}</section><aside className="reference-checkout-summary"><h2>Order summary</h2><ProductRows products={products} compact/><form className="checkout-coupon" onSubmit={apply}><input value={coupon} onChange={event=>setCoupon(event.target.value.toUpperCase())} placeholder="Coupon code"/><button disabled={!account||!coupon.trim()||Boolean(busy)}>{busy==="coupon"?"Applying…":"Apply"}</button></form>{preview?<PriceSummary preview={preview} itemCount={products.length}/>:null}<div className="secure-payment">▣ <span><b>Secure payment powered by Razorpay</b><small>Your payment information is encrypted and secure.</small></span></div><button className="reference-checkout-button" disabled={!account||!preview||products.length===0||Boolean(busy)} onClick={placeOrder}>{busy==="order"?"Creating order…":`Place order & pay${preview?` ${formatMoney(preview.totalPaise,preview.currency)}`:""} →`}</button>{error?<p className="notice danger" role="alert">{error}</p>:null}</aside></div></>;
}

export function ClearCartOnMount(){useEffect(()=>clearCart(),[]);return null;}
