export const TOKEN_PURPOSE = {
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  PASSWORD_RESET: "PASSWORD_RESET",
  MFA_LOGIN: "MFA_LOGIN",
} as const;

export type TokenPurpose = (typeof TOKEN_PURPOSE)[keyof typeof TOKEN_PURPOSE];

export const ADMIN_ROLE_KEYS = new Set(["CONTENT_REVIEWER", "CONTENT_ADMIN", "SUPPORT_AGENT", "FINANCE_ADMIN", "SUPER_ADMIN"]);
