import { logger } from "@/lib/logger";
import { contentConflict, contentNotFound, invalidContentState, isUniqueViolation } from "@/features/admin-content/errors";
import { findExam } from "@/features/admin-content/repository";
import { findCatalogTest, findMaterial, findProduct, findProductBundle, insertMaterial, insertProduct, insertProductLink, listCatalogExams, listMaterials, listProducts, publishMaterialRecord, publishProductRecord, type MaterialInput, type ProductInput } from "./repository";
type Actor = { userId: string; requestId: string };
async function write<T>(action: string, actor: Actor, operation: () => Promise<T>) { try { const result = await operation(); logger.info({ requestId: actor.requestId, module: "admin-catalog", action, actorUserId: actor.userId }, "Admin catalog mutation completed"); return result; } catch (error) { if (isUniqueViolation(error)) throw contentConflict("This package already contains that item or uses an existing slug."); throw error; } }
export const getProducts = () => listProducts(); export const getMaterials = () => listMaterials(); export const getCatalogExams = () => listCatalogExams();
export async function getProduct(id: string) { const product = await findProductBundle(id); if (!product) throw contentNotFound("Product"); return product; }
export const createProduct = (input: ProductInput, actor: Actor) => write("product_create", actor, () => insertProduct(input, { actorUserId: actor.userId, requestId: actor.requestId }));
export async function createMaterial(input: MaterialInput, actor: Actor) { if (!await findExam(input.examId)) throw contentNotFound("Exam"); return write("material_create", actor, () => insertMaterial(input, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function publishMaterial(id: string, actor: Actor) { const before = await findMaterial(id); if (!before) throw contentNotFound("Material"); if (before.status !== "DRAFT") throw invalidContentState("Only draft materials can be published."); const exam = await findExam(before.examId); if (!exam || exam.status !== "PUBLISHED") throw invalidContentState("Publish the material's exam before publishing this material."); return write("material_publish", actor, () => publishMaterialRecord(before, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function linkProduct(id: string, kind: "TEST" | "MATERIAL", targetId: string, actor: Actor) { const product = await findProduct(id); if (!product) throw contentNotFound("Product"); if (product.status !== "DRAFT") throw invalidContentState("Published packages cannot be changed."); const target = kind === "TEST" ? await findCatalogTest(targetId) : await findMaterial(targetId); if (!target || target.status !== "PUBLISHED") throw invalidContentState(`Only published ${kind.toLowerCase()}s can be linked.`); return write("product_link", actor, () => insertProductLink(id, kind, targetId, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function publishProduct(id: string, actor: Actor) { const before = await getProduct(id); if (before.status !== "DRAFT") throw invalidContentState("Only draft packages can be published."); const usableTest = before.linkedTests.some((test) => test.status === "PUBLISHED" && test.examStatus === "PUBLISHED"); const usableMaterial = before.linkedMaterials.some((material) => material.status === "PUBLISHED"); if (!usableTest && !usableMaterial) throw invalidContentState("Link at least one currently published test or material before publishing."); return write("product_publish", actor, () => publishProductRecord(before, { actorUserId: actor.userId, requestId: actor.requestId })); }
