import Link from "next/link";
import { testCategoryLabels, testCategoryLabel } from "@/features/admin-tests/categories";
import { WorkspaceShell } from "@/components/workspace-shell";
import { CONTENT_PERMISSIONS } from "@/features/admin-content/permissions";
import { getManagedTests, getTestExams } from "@/features/admin-tests/service";
import { TestCreateForm } from "@/features/admin-tests/ui/forms";
import { requireAnyWorkspacePermission } from "@/features/auth/page-access";

const access = [CONTENT_PERMISSIONS.manageTests, CONTENT_PERMISSIONS.manageSchedules];
export const metadata = { title: "Test builder" };
export default async function Page({ searchParams }: { searchParams: Promise<{ exam?: string | string[]; q?: string | string[]; category?: string | string[]; status?: string | string[] }> }) {
  const filters = await searchParams;
  const selectedExamId = typeof filters.exam === "string" ? filters.exam : "";
  const category = typeof filters.category === "string" && (filters.category === "UNCLASSIFIED" || Object.hasOwn(testCategoryLabels, filters.category)) ? filters.category : "";
  const query = (typeof filters.q === "string" ? filters.q : "").trim().slice(0, 160);
  const status = typeof filters.status === "string" && ["DRAFT", "PUBLISHED", "ARCHIVED"].includes(filters.status) ? filters.status : "";
  const auth = await requireAnyWorkspacePermission(access); const canManage = auth.permissions.includes(CONTENT_PERMISSIONS.manageTests);
  const [tests, exams] = await Promise.all([getManagedTests().then((rows) => rows.filter((test) => test.mode === "MOCK" && (!category || (category === "UNCLASSIFIED" ? test.category === null : test.category === category)) && (!selectedExamId || test.examId === selectedExamId) && (!status || test.status === status) && (!query || test.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())))), canManage ? getTestExams() : Promise.resolve([])]);
  return <WorkspaceShell admin name={auth.user.name} permissions={auth.permissions} section="tests"><header className="page-heading"><span className="eyebrow">TEST BUILDER</span><h1>{exams.find(exam => exam.id === selectedExamId)?.name ?? "All exams"} · Tests & practice sets</h1><p>Prepare questions, set a time limit and publish your mock test.</p></header><form className="panel inline-admin-form" method="get" action="/admin/tests"><label className="field"><span>Exam</span><select name="exam" defaultValue={selectedExamId ?? ""}><option value="">All exams</option>{exams.map(exam => <option key={exam.id} value={exam.id}>{exam.name}</option>)}</select></label><label className="field"><span>Test type</span><select name="category" defaultValue={category}><option value="">All types</option>{Object.entries(testCategoryLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}<option value="UNCLASSIFIED">Uncategorised</option></select></label><label className="field"><span>Status</span><select name="status" defaultValue={status}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><label className="field"><span>Search test name</span><input name="q" defaultValue={query} maxLength={160} type="search" /></label><button className="button" type="submit">Apply filters</button><Link className="back-link" href="/admin/tests">Clear filters</Link></form><p className="muted">{tests.length} matching test{tests.length === 1 ? "" : "s"}</p><div className="admin-two-column"><section>{tests.length ? <div className="managed-list">{tests.map((test) => <Link className="managed-card" href={`/admin/tests/${test.id}`} key={test.id}><div><span className="eyebrow">{test.examName} · {testCategoryLabel(test.category)}</span><h2>{test.title}</h2><p>{test.durationMinutes} minutes</p></div><dl><div><dt>Sections</dt><dd>{test.sectionCount}</dd></div><div><dt>Questions</dt><dd>{test.questionCount}</dd></div></dl><span className={`status-pill content-${test.status.toLowerCase()}`}>{test.status}</span></Link>)}</div> : <div className="panel empty-state"><h2>No matching tests</h2><p>Change the filters or create a draft test from the builder panel.</p></div>}</section>{canManage && <aside className="panel sticky-panel"><span className="eyebrow">NEW TEST</span><h2>Create a draft</h2>{exams.length ? <TestCreateForm exams={exams} selectedExamId={selectedExamId} /> : <p className="notice">Create an exam before building a test.</p>}</aside>}</div></WorkspaceShell>;
}
