import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentOrder } from "@/features/commerce/service";
import { commerceIdSchema } from "@/features/commerce/validation";
import { formatMoney } from "@/features/commerce/pricing";
import { PrintInvoiceButton } from "@/features/commerce/ui/print-invoice";

type Order={id:string;status:string;subtotalPaise:number;discountPaise:number;totalPaise:number;currency:string;couponCode:string|null;createdAt:Date;paidAt:Date|null;provider:string|null;providerPaymentId:string|null;items:{productId:string;name:string;pricePaise:number;accessDays:number}[]};
export const metadata={title:"Invoice"};
export default async function Page({params}:{params:Promise<{id:string}>}){const auth=await requireWorkspace();if(auth.admin)redirect("/admin");const parsed=commerceIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const raw=await getStudentOrder(parsed.data,auth.user.id);if(!raw)notFound();const order=raw as unknown as Order;if(order.status!=="PAID"&&order.status!=="REFUNDED"&&order.status!=="PARTIALLY_REFUNDED")notFound();return <WorkspaceShell admin={false} name={auth.user.name} section="orders"><div className="invoice-actions"><Link className="back-link" href={`/dashboard/orders/${order.id}`}>← Order details</Link><PrintInvoiceButton/></div><article className="invoice"><header><div className="invoice-brand"><strong><span>Prep</span>store</strong><small>Digital Exam-Preparation Store</small></div><div><span>TAX INVOICE</span><strong>#{order.id.slice(0,12).toUpperCase()}</strong></div></header><section className="invoice-meta"><div><span>Billed to</span><strong>{auth.user.name}</strong><small>{auth.user.email}</small></div><div><span>Invoice date</span><strong>{new Date(order.paidAt??order.createdAt).toLocaleDateString("en-IN",{dateStyle:"long"})}</strong><small>Order {order.id}</small></div></section><table><thead><tr><th>Digital package</th><th>Access</th><th>Amount</th></tr></thead><tbody>{order.items.map((item)=><tr key={item.productId}><td>{item.name}</td><td>{item.accessDays} days</td><td>{formatMoney(item.pricePaise,order.currency)}</td></tr>)}</tbody></table><section className="invoice-total"><dl><div><dt>Subtotal</dt><dd>{formatMoney(order.subtotalPaise,order.currency)}</dd></div>{order.discountPaise>0?<div><dt>Coupon discount {order.couponCode?`(${order.couponCode})`:""}</dt><dd>− {formatMoney(order.discountPaise,order.currency)}</dd></div>:null}<div><dt>Total paid</dt><dd>{formatMoney(order.totalPaise,order.currency)}</dd></div></dl></section><footer><p>This invoice is for digital educational content. No physical delivery is involved.</p><small>Payment reference: {order.providerPaymentId??"Free order"}</small></footer></article></WorkspaceShell>}
