"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
type Material={id:string;title:string;subject:string;topic:string;type:"PDF"|"VIDEO"|"FILE";version:number|null;originalFileName:string|null;sizeBytes:number|null;lastAccessed:string|null;viewed:boolean};
function bytes(value:number|null){if(!value)return "Online";return value<1024*1024?`${Math.ceil(value/1024)} KB`:`${(value/1024/1024).toFixed(1)} MB`}
export function MaterialsBrowser({materials,courseSlug}:{materials:Material[];courseSlug:string}){
 const[query,setQuery]=useState("");const[type,setType]=useState<"ALL"|Material["type"]>("ALL");const[selectedSubject,setSelectedSubject]=useState<string|null>(null);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return materials.filter(item=>(type==="ALL"||item.type===type)&&(!selectedSubject||item.subject===selectedSubject)&&(!q||`${item.title} ${item.subject} ${item.topic} ${item.originalFileName??""}`.toLowerCase().includes(q)))},[materials,query,type,selectedSubject]);
 const groups=useMemo(()=>Array.from(new Set(materials.map(item=>item.subject))).map(subject=>{const entries=materials.filter(item=>item.subject===subject),opened=entries.filter(item=>item.viewed).length;return{subject,entries,progress:entries.length?Math.round(opened/entries.length*100):0,last:entries.map(item=>item.lastAccessed).filter((value):value is string=>Boolean(value)).sort().at(-1)??null}}),[materials]);
 const tabs:["ALL"|Material["type"],string][]=[["ALL","All"],["PDF","PDFs"],["VIDEO","Videos"],["FILE","Notes"]],showFiles=Boolean(selectedSubject||query||type!=="ALL");
 return <section className="materials-browser"><div className="materials-heading"><div><h2>{selectedSubject??"Course resources"}</h2><p>{selectedSubject?"Browse every resource in this subject.":"Select a subject or search across all package resources."}</p></div><label className="materials-search"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search topics, files or keywords…" aria-label="Search study materials"/></label></div><div className="materials-tools"><nav>{tabs.map(([key,label])=><button className={type===key?"active":""} type="button" aria-pressed={type===key} onClick={()=>setType(key)} key={key}>{label}</button>)}</nav>{selectedSubject?<button className="subject-back" type="button" onClick={()=>setSelectedSubject(null)}>← All subjects</button>:<span>{materials.length} resources</span>}</div>{!showFiles?<div className="materials-table subject-table"><div className="materials-table-head"><span>Name</span><span>Items</span><span>Progress</span><span>Last accessed</span><span>Open</span></div>{groups.map(group=><button type="button" onClick={()=>setSelectedSubject(group.subject)} key={group.subject}><i aria-hidden="true">▰</i><strong>{group.subject}<small>{new Set(group.entries.map(item=>item.topic)).size} topics</small></strong><span>{group.entries.length} items</span><span><progress max="100" value={group.progress}/>{group.progress}%</span><span>{group.last?new Date(group.last).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"Not opened"}</span><b>›</b></button>)}</div>:visible.length?<div className="materials-table"><div className="materials-table-head"><span>Name</span><span>Type</span><span>Size</span><span>Last accessed</span><span>Open</span></div>{visible.map(material=><Link href={`/library/${material.id}?course=${courseSlug}`} key={material.id}><i aria-hidden="true">▰</i><strong>{material.title}<small>{material.topic}</small></strong><span>{material.type}</span><span>{bytes(material.sizeBytes)}</span><span>{material.lastAccessed?new Date(material.lastAccessed).toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Not opened"}</span><b>›</b></Link>)}</div>:<section className="student-empty-row"><p>No study materials match this search.</p></section>}</section>
}
