import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import type { CSSProperties } from "react";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentNotifications } from "@/features/operations/service";
import { getStudentCourse } from "@/features/student-courses/service";
import { MaterialsBrowser } from "@/features/student-courses/ui/materials-browser";

const views = ["overview", "materials", "tests", "results"] as const;
type CourseView = (typeof views)[number];
const isView = (value: string | undefined): value is CourseView => views.includes(value as CourseView);
function WorkspaceIcon({name}:{name:"book"|"test"|"result"|"play"}){const paths={book:<><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 5.5v16"/></>,test:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h3"/></>,result:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>,play:<><circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}

export default async function Page({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ view?: string }> }) {
  const auth = await requireWorkspace();
  if (auth.admin) redirect("/admin");
  const { slug } = await params;
  const query = await searchParams;
  const view: CourseView = isView(query.view) ? query.view : "overview";
  const [course,notifications] = await Promise.all([getStudentCourse(slug, auth.user.id),getStudentNotifications(auth.user.id)]);
  if (!course) notFound();
  const progress=course.testCount?Math.min(100,Math.round(course.completedAttempts/course.testCount*100)):0;
  const syllabus=(course.syllabus??"").split(/\r?\n/).map(item=>item.trim()).filter(Boolean);
  const recentActivity=[...(course.results.slice(0,3).map(result=>({id:result.id,title:`Completed ${result.title}`,meta:`Score ${result.score} / ${result.maxScore}`,date:result.publishedAt,href:`/results/${result.id}?course=${slug}`,icon:"result" as const}))),...(course.activeAttemptId?[{id:course.activeAttemptId,title:`Continued ${course.activeTestTitle??"test"}`,meta:"Attempt in progress",date:null,href:`/attempts/${course.activeAttemptId}?course=${slug}`,icon:"test" as const}]:[])].slice(0,3);
  return <WorkspaceShell admin={false} name={auth.user.name} section="courses" unreadNotifications={notifications.unreadCount} activePackageSlug={slug} activePackageView={view}>
    <nav className="student-breadcrumb" aria-label="Breadcrumb"><Link href="/dashboard">Dashboard</Link><span>›</span><Link href="/dashboard/courses">My Packages</Link><span>›</span><b>{course.name}</b></nav>
    <header className="package-content-heading"><div><span>{course.accessSource==="FREE"?"FREE PACKAGE":"MY PACKAGE"}</span><h1>{view==="overview"?course.name:view==="materials"?"Study materials":view==="tests"?"Tests & practice sets":"Results & analysis"}</h1><p>{view==="overview"?(course.description||"Your learning package overview."):view==="materials"?"Browse your package resources by subject and topic.":view==="tests"?"Continue mock tests and practice sets included in this package.":"Review your completed test performance."}</p></div></header>

    {view==="overview"?<>
      <section className="student-overview-progress"><div className="progress-ring" style={{"--progress":`${progress*3.6}deg`} as CSSProperties}><span><b>{progress}%</b><small>complete</small></span></div><div><h2>Your progress</h2><p>Continue learning and completing tests to move forward.</p><div><span><b>{course.completedAttempts}</b> tests completed</span><span><b>{Math.max(0,course.testCount-course.completedAttempts)}</b> tests remaining</span><span><b>{course.materialCount}</b> resources available</span></div></div>{course.activeAttemptId?<Link href={`/attempts/${course.activeAttemptId}?course=${slug}`}>Resume test <b>→</b></Link>:null}</section>
      <section className="student-section"><div className="student-section-heading"><div><h2>Package content</h2><p>Everything included in your learning package</p></div><Link href={`/dashboard/courses/${slug}?view=materials`}>View all <span>→</span></Link></div><div className="package-content-list">{syllabus.length?syllabus.slice(0,5).map((topic,index)=><article key={`${topic}-${index}`}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{topic}</strong><small>Package syllabus topic</small></div><i><WorkspaceIcon name="book"/></i></article>):<><article><span>01</span><div><strong>Study materials</strong><small>{course.materialCount} learning resources</small></div><i><WorkspaceIcon name="book"/></i></article><article><span>02</span><div><strong>Tests & practice</strong><small>{course.testCount} tests</small></div><i><WorkspaceIcon name="test"/></i></article></>}</div></section>
      <section className="student-section"><div className="student-section-heading"><div><h2>Recent activity</h2><p>Your latest progress in this package</p></div><Link href={`/dashboard/courses/${slug}?view=results`}>View all <span>→</span></Link></div>{recentActivity.length?<div className="package-activity-list">{recentActivity.map(item=><Link href={item.href} key={item.id}><i><WorkspaceIcon name={item.icon}/></i><div><strong>{item.title}</strong><small>{item.meta}</small></div><span>{item.date?new Date(item.date).toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Now"}</span></Link>)}</div>:<div className="student-empty-row"><p>Your learning activity will appear here.</p></div>}</section>
    </>:null}

    {view === "materials" ? <MaterialsBrowser materials={course.materials.map(item=>({...item,lastAccessed:item.lastAccessed?new Date(item.lastAccessed).toISOString():null}))} courseSlug={slug}/> : null}
    {view === "tests" ? course.tests.length ? <div className="student-test-grid premium-test-list">{course.tests.map((test) => {const remaining=Math.max(0,test.maxAttempts-test.attemptsUsed);return <article className="student-test-card" key={test.id}><i className="student-test-icon"><WorkspaceIcon name="test"/></i><div className="student-test-copy"><span>{test.category?.replaceAll("_", " ") || test.mode}</span><h2>{test.title}</h2><div className="student-test-facts"><small><b>{test.questionCount}</b> questions</small><small><b>{test.durationMinutes}</b> minutes</small><small><b>{remaining}</b> attempts left</small></div></div><div className="student-test-state"><span className={test.activeAttemptId?"in-progress":test.latestResultId?"completed":"ready"}>{test.activeAttemptId?"In progress":test.latestResultId?"Attempted":"Ready"}</span>{test.latestResultId?<Link href={`/results/${test.latestResultId}?course=${slug}`}>View result</Link>:null}</div><div className="student-test-action">{test.activeAttemptId ? <Link className="button" href={`/attempts/${test.activeAttemptId}?course=${slug}`}>Resume test <b>→</b></Link> : remaining ? <Link className="button" href={`/tests/${test.id}?course=${slug}`}>View instructions <b>→</b></Link> : <span className="quiet-tag">Attempts completed</span>}</div></article>})}</div> : <section className="panel empty-state"><h2>No tests assigned</h2><p>Tests and practice sets included in this package will appear here.</p></section> : null}
    {view === "results" ? course.results.length ? <div className="result-list">{course.results.map((result) => { const percentage = Number(result.maxScore) ? Math.round((Number(result.score) / Number(result.maxScore)) * 100) : 0; return <article className="panel result-card" key={result.id}><div><span className="eyebrow">ATTEMPT {result.sequence}</span><h2>{result.title}</h2><p>{new Date(result.publishedAt).toLocaleString("en-IN")}</p></div><div className="result-score"><strong>{percentage}%</strong><span>{result.score} / {result.maxScore}</span></div><div className="result-mini"><span>{result.correctCount} correct</span><span>{result.incorrectCount} incorrect</span></div><Link className="button secondary" href={`/results/${result.id}?course=${slug}`}>View analysis</Link></article>; })}</div> : <section className="panel empty-state"><h2>No results yet</h2><p>Evaluated test attempts from this package will appear here.</p><Link className="button" href={`/dashboard/courses/${slug}?view=tests`}>View tests</Link></section> : null}
  </WorkspaceShell>;
}
