import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentCourse } from "@/features/student-courses/service";

const views = ["overview", "materials", "tests", "results"] as const;
type CourseView = (typeof views)[number];
const isView = (value: string | undefined): value is CourseView => views.includes(value as CourseView);
function bytes(value: number | null) { if (!value) return "Online resource"; return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }

export default async function Page({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ view?: string }> }) {
  const auth = await requireWorkspace();
  if (auth.admin) redirect("/admin");
  const { slug } = await params;
  const query = await searchParams;
  const view: CourseView = isView(query.view) ? query.view : "overview";
  const course = await getStudentCourse(slug, auth.user.id);
  if (!course) notFound();
  return <WorkspaceShell admin={false} name={auth.user.name} section="courses">
    <Link className="back-link" href="/dashboard/courses">← My courses</Link>
    <section className="course-detail-hero"><div><span className="eyebrow">{course.accessSource === "FREE" ? "FREE ACCESS" : "ENROLLED COURSE"}</span><h1>{course.name}</h1><p>{course.description || "Your complete learning course."}</p></div><dl><div><dt>Materials</dt><dd>{course.materialCount}</dd></div><div><dt>Tests</dt><dd>{course.testCount}</dd></div><div><dt>Completed</dt><dd>{course.completedAttempts}</dd></div></dl></section>
    <nav className="course-tabs" aria-label="Course sections">{([{ key: "overview", label: "Overview" }, { key: "materials", label: "Study materials" }, { key: "tests", label: "Tests & practice" }, { key: "results", label: "Results & analysis" }] as const).map((tab) => <Link key={tab.key} className={view === tab.key ? "active" : ""} aria-current={view === tab.key ? "page" : undefined} href={`/dashboard/courses/${slug}?view=${tab.key}`}>{tab.label}</Link>)}</nav>
    {view === "overview" ? <div className="course-overview-grid"><section className="panel"><span className="eyebrow">COURSE OVERVIEW</span><h2>Everything for this course, in one workspace</h2><p className="muted">Open study resources, attempt assigned tests and revisit detailed results without moving between separate libraries.</p><div className="course-overview-actions"><Link className="button" href={`/dashboard/courses/${slug}?view=materials`}>Start learning</Link><Link className="button secondary" href={`/dashboard/courses/${slug}?view=tests`}>View tests</Link></div></section><aside className="panel course-next-card"><span className="eyebrow">CONTINUE</span>{course.activeAttemptId ? <><h2>{course.activeTestTitle}</h2><p>An attempt is in progress. Your saved answers are ready.</p><Link className="button" href={`/attempts/${course.activeAttemptId}?course=${slug}`}>Resume test</Link></> : course.tests[0] ? <><h2>{course.tests[0].title}</h2><p>{course.tests[0].durationMinutes} minutes · {course.tests[0].questionCount} questions</p><Link className="button" href={`/tests/${course.tests[0].id}?course=${slug}`}>View instructions</Link></> : <><h2>No test assigned</h2><p>Study materials remain available below.</p></>}</aside></div> : null}
    {view === "materials" ? course.materials.length ? <div className="student-material-grid">{course.materials.map((material) => <article className="panel student-material-card" key={material.id}><div><span className="eyebrow">{material.type}</span><h2>{material.title}</h2><p className="muted">{material.originalFileName || "Prepstore study resource"}</p></div><div className="student-material-meta"><span>Version {material.version ?? 1} · {bytes(material.sizeBytes)}</span><Link className="button" href={`/library/${material.id}?course=${slug}`}>Open material</Link></div></article>)}</div> : <section className="panel empty-state"><h2>No study materials yet</h2><p>Materials assigned to this course will appear here.</p></section> : null}
    {view === "tests" ? course.tests.length ? <div className="student-test-grid">{course.tests.map((test) => <article className="panel student-test-card" key={test.id}><div><span className="eyebrow">{test.category?.replaceAll("_", " ") || test.mode}</span><h2>{test.title}</h2><p>{test.questionCount} questions · {test.durationMinutes} minutes</p></div><div className="student-test-meta"><span>{test.attemptsUsed} of {test.maxAttempts} attempts used</span>{test.latestResultId ? <Link className="text-button" href={`/results/${test.latestResultId}?course=${slug}`}>Latest result</Link> : null}</div>{test.activeAttemptId ? <Link className="button" href={`/attempts/${test.activeAttemptId}?course=${slug}`}>Resume test</Link> : test.attemptsUsed < test.maxAttempts ? <Link className="button" href={`/tests/${test.id}?course=${slug}`}>View instructions</Link> : <span className="quiet-tag">Attempts completed</span>}</article>)}</div> : <section className="panel empty-state"><h2>No tests assigned</h2><p>Tests and practice sets included in this course will appear here.</p></section> : null}
    {view === "results" ? course.results.length ? <div className="result-list">{course.results.map((result) => { const percentage = Number(result.maxScore) ? Math.round((Number(result.score) / Number(result.maxScore)) * 100) : 0; return <article className="panel result-card" key={result.id}><div><span className="eyebrow">ATTEMPT {result.sequence}</span><h2>{result.title}</h2><p>{new Date(result.publishedAt).toLocaleString("en-IN")}</p></div><div className="result-score"><strong>{percentage}%</strong><span>{result.score} / {result.maxScore}</span></div><div className="result-mini"><span>{result.correctCount} correct</span><span>{result.incorrectCount} incorrect</span></div><Link className="button secondary" href={`/results/${result.id}?course=${slug}`}>View analysis</Link></article>; })}</div> : <section className="panel empty-state"><h2>No results yet</h2><p>Evaluated test attempts from this course will appear here.</p><Link className="button" href={`/dashboard/courses/${slug}?view=tests`}>View tests</Link></section> : null}
  </WorkspaceShell>;
}
