import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminModal } from "@/components/admin-modal";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireWorkspace } from "@/features/auth/page-access";
import { getStudentOrders } from "@/features/commerce/service";
import { getStudentNotifications, getStudentSupportTickets } from "@/features/operations/service";
import { NewSupportTicketForm } from "@/features/operations/ui/student-actions";

export const metadata={title:"Support centre"};
function SupportIcon({name}:{name:"search"|"payment"|"access"|"account"|"technical"}){const paths={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,payment:<><rect x="3" y="6" width="18" height="13" rx="2"/><path d="M3 10h18M7 15h3"/></>,access:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,account:<><circle cx="12" cy="12" r="3"/><path d="M19 13.5a7.4 7.4 0 0 0 0-3l2-1.5-2-3.5-2.5 1A7 7 0 0 0 14 5l-.5-3h-4L9 5a7 7 0 0 0-2.5 1.5l-2.5-1L2 9l2 1.5a7.4 7.4 0 0 0 0 3L2 15l2 3.5 2.5-1A7 7 0 0 0 9 19l.5 3h4l.5-3a7 7 0 0 0 2.5-1.5l2.5 1 2-3.5z"/></>,technical:<><path d="M14 6 6 14M16 4a4 4 0 0 0 4 4l-8 8-4-4z"/><path d="m5 15-2 2 4 4 2-2"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}

export default async function Page({searchParams}:{searchParams:Promise<{q?:string}>}){
  const auth=await requireWorkspace();if(auth.admin)redirect("/admin");const query=(await searchParams).q?.trim()??"";
  const[tickets,orders,notifications]=await Promise.all([getStudentSupportTickets(auth.user.id),getStudentOrders(auth.user.id),getStudentNotifications(auth.user.id)]);
  const orderOptions=orders.map(order=>{const value=order as {id:string;createdAt:Date;items:{name:string}[]};return{id:value.id,label:`${value.items.map(item=>item.name).join(", ")} · ${new Date(value.createdAt).toLocaleDateString("en-IN")}`}});
  const normalized=query.toLowerCase();const visible=normalized?tickets.filter(ticket=>ticket.subject.toLowerCase().includes(normalized)||ticket.category.toLowerCase().includes(normalized)||ticket.status.toLowerCase().includes(normalized)):tickets;
  return <WorkspaceShell admin={false} name={auth.user.name} section="support" unreadNotifications={notifications.unreadCount}>
    <header className="student-page-heading"><div><h1>Support Centre</h1><p>Find answers, explore helpful resources or raise a ticket.</p></div></header>
    <form className="support-reference-search"><SupportIcon name="search"/><input name="q" defaultValue={query} placeholder="How can we help?"/><button>Search</button><small>Search topics like payments, packages, access or technical issues.</small></form>
    <section className="support-topic-section"><div className="student-section-heading"><h2>Popular topics</h2><Link href="/dashboard/support">View all</Link></div><div className="support-topic-grid"><Link href="/dashboard/support?q=payment"><i><SupportIcon name="payment"/></i><span><b>Payments &amp; Orders</b><small>Billing, invoices, payment issues</small></span></Link><Link href="/dashboard/support?q=access"><i><SupportIcon name="access"/></i><span><b>Package Access</b><small>How to access your purchased packages</small></span></Link><Link href="/dashboard/support?q=account"><i><SupportIcon name="account"/></i><span><b>Account &amp; Settings</b><small>Profile, security, login issues</small></span></Link><Link href="/dashboard/support?q=technical"><i><SupportIcon name="technical"/></i><span><b>Technical Issues</b><small>Video, quizzes and other help</small></span></Link></div></section>
    <section className="support-ticket-section"><div className="student-section-heading"><h2>Your Support Tickets</h2><AdminModal label="＋ Create new ticket" title="Create support ticket" description="Tell us what happened and we will keep the conversation organised here." large><NewSupportTicketForm orders={orderOptions}/></AdminModal></div>{visible.length?<div className="support-ticket-table"><table><thead><tr><th>Ticket ID</th><th>Subject</th><th>Status</th><th>Last update</th><th>Action</th></tr></thead><tbody>{visible.map(ticket=><tr key={ticket.id}><td>#{ticket.id.slice(0,6).toUpperCase()}</td><td>{ticket.subject}</td><td><b className={`support-status ${ticket.status.toLowerCase()}`}>{ticket.status.replaceAll("_"," ")}</b></td><td>{new Date(ticket.updatedAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</td><td><Link href={`/dashboard/support/${ticket.id}`}>View</Link></td></tr>)}</tbody></table></div>:<div className="student-empty-package"><h2>No support tickets found</h2><p>{query?"Try another search term.":"Create a ticket whenever you need help."}</p></div>}</section>
  </WorkspaceShell>;
}
