"use client";
import { ContentPicker, SearchableContentSelect, type SellableItems } from "./content-picker";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Field } from "@/features/auth/ui/field";
import type { ApiFailure, ApiSuccess } from "@/lib/http/api-response";

type Exam = { id: string; name: string }; type LinkOption = { id: string; title: string; examName?: string; mode?: string; type?: string };
async function request<T>(path: string, body: Record<string, unknown>, method: "POST" | "PATCH" | "DELETE" = "POST") { const response = await fetch(`/api/admin/catalog/${path}`, { method, credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as ApiSuccess<T> | ApiFailure; if (!response.ok || "error" in payload) throw new Error("error" in payload ? payload.error.message : "Couldn't complete this request."); return payload.data; }
async function upload<T>(path: string, body: FormData) { const response = await fetch(`/api/admin/catalog/${path}`, { method: "POST", credentials: "same-origin", body }); const payload = await response.json() as ApiSuccess<T> | ApiFailure; if (!response.ok || "error" in payload) throw new Error("error" in payload ? payload.error.message : "Couldn't upload this file."); return payload.data; }
function useMutation() { const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); async function mutate<T>(key: string, operation: () => Promise<T>) { setBusy(key); setError(""); try { const result = await operation(); router.refresh(); return result; } catch (cause) { setError(cause instanceof Error ? cause.message : "Couldn't save this change."); return undefined; } finally { setBusy(""); } } return { router, busy, error, mutate }; }

export function ProductCreateForm({ product, items }: { items?: SellableItems; product?: { id: string; name: string; slug: string; description: string | null; pricePaise: number; accessDays: number } } = {}) { const { router, busy, error, mutate } = useMutation(); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await mutate<{ id: string }>("product", () => request(product ? `products/${product.id}` : "products", { name: String(data.get("name")), slug: String(data.get("slug")), description: String(data.get("description") ?? ""), pricePaise: Math.round(Number(data.get("priceRupees")) * 100), accessDays: Number(data.get("accessDays")), ...(!product ? { testIds: data.getAll("testIds"), materialIds: data.getAll("materialIds") } : {}) }, product ? "PATCH" : "POST")); if (result) router.push(`/admin/packages/${result.id}`); } return <form className="admin-form" onSubmit={submit}><fieldset disabled={Boolean(busy)}><Field id="product-name" label="Product / bundle name" name="name" defaultValue={product?.name} required /><Field id="product-slug" label="URL slug" name="slug" defaultValue={product?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /><div className="question-grid"><Field id="product-price" label="Price (INR)" name="priceRupees" defaultValue={product ? product.pricePaise / 100 : undefined} type="number" min={0} step="0.01" required /><Field id="product-days" label="Access days" name="accessDays" type="number" min={1} max={3650} defaultValue={product?.accessDays ?? 90} required /></div><label className="field"><span>Description</span><textarea name="description" defaultValue={product?.description ?? ""} maxLength={4000} rows={3} /></label>{!product && items && <ContentPicker items={items} />}<button className="button" type="submit">{busy ? "Saving…" : product ? "Save package" : "Create draft product / bundle"}</button></fieldset>{error && <p className="notice danger" role="alert">{error}</p>}</form>; }

export function MaterialCreateForm({ exams, material }: { exams: Exam[]; material?: { id: string; examId: string; title: string; type: string; body: string | null; privateObjectKey: string | null; allowDownload: boolean } }) { const { busy, error, mutate } = useMutation(); const [type, setType] = useState(material?.type === "VIDEO" ? "VIDEO" : "ARTICLE"); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const result = await mutate("material", () => request(material ? `materials/${material.id}` : "materials", { examId: String(data.get("examId")), title: String(data.get("title")), type, body: String(data.get("body") ?? ""), privateObjectKey: "", allowDownload: false }, material ? "PATCH" : "POST")); if (result && !material) form.reset(); } return <form className="admin-form" onSubmit={submit}><fieldset disabled={Boolean(busy)}><label className="field"><span>Exam</span><select name="examId" defaultValue={material?.examId}>{exams.map((exam) => <option value={exam.id} key={exam.id}>{exam.name}</option>)}</select></label><Field id="material-title" label="Material title" name="title" defaultValue={material?.title} required /><label className="field"><span>Type</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="ARTICLE">Article</option><option value="VIDEO">Video link</option></select></label><label className="field"><span>{type === "ARTICLE" ? "Article body" : "HTTPS video URL"}</span><textarea name="body" defaultValue={material?.body ?? ""} rows={4} /></label><button className="button" type="submit">{busy ? "Saving…" : material ? "Save material" : "Create draft article / video"}</button></fieldset>{error && <p className="notice danger" role="alert">{error}</p>}</form>; }

export function MaterialUploadForm({ exams, material }: { exams?: Exam[]; material?: { id: string; title: string; allowDownload: boolean } }) { const { router, busy, error, mutate } = useMutation(); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); data.set("allowDownload", data.get("allowDownload") ? "true" : "false"); const result = await mutate<{ id: string }>("upload", () => upload(material ? `materials/${material.id}/upload` : "materials/upload", data)); if (result) { if (material) router.refresh(); else router.push(`/admin/materials/${result.id}`); } } return <form className="admin-form material-upload-form" onSubmit={submit}><fieldset disabled={Boolean(busy)}>{!material && <label className="field"><span>Exam</span><select name="examId" required>{exams?.map((exam) => <option value={exam.id} key={exam.id}>{exam.name}</option>)}</select></label>}<Field id={material ? "replacement-title" : "upload-title"} label="Material title" name="title" defaultValue={material?.title} required /><label className="field"><span>Study file</span><input name="file" type="file" accept=".pdf,.zip,.txt,.docx,.pptx,application/pdf" required /><small>PDF, ZIP, TXT, DOCX or PPTX. The file stays private.</small></label><label className="check-row"><input name="allowDownload" type="checkbox" defaultChecked={material?.allowDownload} />Allow students to download their watermarked copy (PDF) or protected file</label><button className="button" type="submit">{busy ? "Uploading…" : material ? "Upload new version" : "Upload draft material"}</button></fieldset>{error && <p className="notice danger" role="alert">{error}</p>}</form>; }

export function MaterialPublishButton({ id }: { id: string }) { const { busy, error, mutate } = useMutation(); return <div><button type="button" className="button secondary" disabled={Boolean(busy)} onClick={() => mutate("publish", () => request(`materials/${id}/publish`, {}))}>{busy ? "Publishing…" : "Publish"}</button>{error && <p className="notice danger" role="alert">{error}</p>}</div>; }

export function ProductBundleControls({ id, status, linkedTests, linkedMaterials, availableTests, availableMaterials }: { id: string; status: string; linkedTests: LinkOption[]; linkedMaterials: LinkOption[]; availableTests: LinkOption[]; availableMaterials: LinkOption[] }) { const { busy, error, mutate } = useMutation(); const draft = status === "DRAFT"; const linked = new Set([...linkedTests, ...linkedMaterials].map((item) => item.id)); const tests = availableTests.filter((item) => !linked.has(item.id)); const materials = availableMaterials.filter((item) => !linked.has(item.id)); async function link(event: FormEvent<HTMLFormElement>, kind: "TEST" | "MATERIAL") { event.preventDefault(); const data = new FormData(event.currentTarget); await mutate(kind, () => request(`products/${id}/links`, { kind, id: String(data.get("id")) })); } return <div className="bundle-controls"><section className="panel"><span className="eyebrow">PACKAGE CONTENTS</span><h2>Linked access</h2>{linkedTests.map((item) => <div className="bundle-item" key={item.id}><span>TEST</span><strong>{item.title}</strong><small>{item.mode}</small>{draft && <button type="button" className="text-button" disabled={Boolean(busy)} onClick={() => mutate("unlink", () => request(`products/${id}/links`, { kind: "TEST", id: item.id }, "DELETE"))}>Remove</button>}</div>)}{linkedMaterials.map((item) => <div className="bundle-item" key={item.id}><span>MATERIAL</span><strong>{item.title}</strong><small>{item.type}</small>{draft && <button type="button" className="text-button" disabled={Boolean(busy)} onClick={() => mutate("unlink", () => request(`products/${id}/links`, { kind: "MATERIAL", id: item.id }, "DELETE"))}>Remove</button>}</div>)}{!linkedTests.length && !linkedMaterials.length && <p className="muted">Nothing linked yet.</p>}</section>{draft && <><section className="panel"><h2>Link a published test</h2>{tests.length ? <form className="inline-admin-form" onSubmit={(event) => link(event, "TEST")}><fieldset disabled={Boolean(busy)}><SearchableContentSelect items={tests} label="Test" /><button className="button secondary" type="submit">Link test</button></fieldset></form> : <p className="muted">No unlinked published tests.</p>}</section><section className="panel"><h2>Link published material</h2>{materials.length ? <form className="inline-admin-form" onSubmit={(event) => link(event, "MATERIAL")}><fieldset disabled={Boolean(busy)}><SearchableContentSelect items={materials} label="Material" /><button className="button secondary" type="submit">Link material</button></fieldset></form> : <p className="muted">No unlinked published materials.</p>}</section><button type="button" className="button" disabled={Boolean(busy)} onClick={() => mutate("publish", () => request(`products/${id}/publish`, {}))}>{busy === "publish" ? "Publishing…" : "Publish package"}</button></>}{error && <p className="notice danger" role="alert">{error}</p>}</div>; }


export function CatalogActions({ id, kind, status }: { id: string; kind: "materials" | "products"; status: string }) {
  const { router, busy, error, mutate } = useMutation();
  async function duplicate() {
    const result = await mutate<{ id: string }>("copy", () => request(`${kind}/${id}/duplicate`, {}));
    if (result) router.push(`/admin/${kind === "materials" ? "materials" : "packages"}/${result.id}`);
  }
  return <div className="form-actions">
    {status !== "DRAFT" && <button type="button" className="button secondary" disabled={Boolean(busy)} onClick={duplicate}>Create editable copy</button>}
    {status !== "ARCHIVED" && <button type="button" className="button secondary" disabled={Boolean(busy)} onClick={() => mutate("archive", () => request(`${kind}/${id}/archive`, {}))}>Archive</button>}
    {error && <p className="notice danger" role="alert">{error}</p>}
  </div>;
}
