import { logger } from "@/lib/logger";
import { contentConflict, isUniqueViolation } from "@/features/admin-content/errors";
import { findExam } from "@/features/admin-content/repository";
import { testNotFound, testStateConflict } from "./errors";
import { findManagedTest, findPublishedQuestionForExam, findSection, findTest, insertAssignment, insertSchedule, insertSection, insertTest, listManagedTests, listTestExams, patchTest, publishTestRecord, type ScheduleInput, type SectionInput, type TestInput } from "./repository";

type Actor = { userId: string; requestId: string };
async function write<T>(action: string, actor: Actor, operation: () => Promise<T>) { try { const result = await operation(); logger.info({ requestId: actor.requestId, module: "admin-tests", action, actorUserId: actor.userId }, "Admin test mutation completed"); return result; } catch (error) { if (isUniqueViolation(error)) throw contentConflict("This item already exists or uses the same display order."); throw error; } }
export const getTestExams = () => listTestExams();
export const getManagedTests = () => listManagedTests();
export async function getManagedTest(id: string) { const test = await findManagedTest(id); if (!test) throw testNotFound("Test"); return test; }
export async function createTest(input: TestInput, actor: Actor) { if (!await findExam(input.examId)) throw testNotFound("Test"); return write("test_create", actor, () => insertTest(input, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function updateTest(id: string, input: TestInput, actor: Actor) { const before = await findTest(id); if (!before) throw testNotFound("Test"); if (before.status !== "DRAFT") throw testStateConflict("Only draft tests can be edited."); if (!await findExam(input.examId)) throw testNotFound("Test"); if (before.examId !== input.examId) { const detail = await getManagedTest(id); if (detail.sections.some((section) => section.questions.length)) throw testStateConflict("Remove assigned questions before changing the exam."); } return write("test_update", actor, () => patchTest(before, input, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function createSection(testId: string, input: SectionInput, actor: Actor) { const test = await findTest(testId); if (!test) throw testNotFound("Test"); if (test.status !== "DRAFT") throw testStateConflict("Published tests cannot be restructured."); return write("test_section_create", actor, () => insertSection(testId, input, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function assignQuestion(sectionId: string, questionId: string, sortOrder: number, actor: Actor) { const section = await findSection(sectionId); if (!section) throw testNotFound("Section"); const test = await findTest(section.testId); if (!test) throw testNotFound("Test"); if (test.status !== "DRAFT") throw testStateConflict("Published tests cannot be restructured."); const question = await findPublishedQuestionForExam(questionId, test.examId); if (!question) throw testNotFound("Question"); return write("test_question_assign", actor, () => insertAssignment(test.id, sectionId, questionId, sortOrder, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function createSchedule(testId: string, input: ScheduleInput, actor: Actor) { const test = await findTest(testId); if (!test) throw testNotFound("Test"); if (test.mode !== "LIVE") throw testStateConflict("Schedules can only be added to live tests."); if (test.status !== "PUBLISHED") throw testStateConflict("Publish the live test before adding a schedule."); return write("test_schedule_create", actor, () => insertSchedule(testId, input, { actorUserId: actor.userId, requestId: actor.requestId })); }
export async function publishTest(id: string, actor: Actor) { const before = await getManagedTest(id); if (before.status !== "DRAFT") throw testStateConflict("Only draft tests can be published."); if (!before.sections.length || !before.sections.some((section) => section.questions.length)) throw testStateConflict("Add at least one section and published question before publishing."); const timed = before.sections.map((section) => section.durationMinutes); if (timed.some((minutes) => minutes !== null) && timed.reduce<number>((total, minutes) => total + (minutes ?? 0), 0) > before.durationMinutes) throw testStateConflict("Section durations cannot exceed the overall test duration."); return write("test_publish", actor, () => publishTestRecord(before, { actorUserId: actor.userId, requestId: actor.requestId })); }
